### ISSUE TITLE
멀티프로세싱 이슈

### ISSUE THREAD

**Issue by hyunwoongko** [bab2min/kiwipiepy#103]
2021년 M1 맥북에서 다음 코드가 작동하지 않습니다.
테스트한 Python 버전은 3.7.3입니다.
kiwi 이용시 멀티프로세싱을 사용하지 않는 방법은 없나요?

```python
from kiwipiepy import Kiwi

kiwi = Kiwi(num_workers=1)
kiwi.tokenize(["아버지가방에들어가시다.", "아버지가방에들어가시다."])
```
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by bab2min** [comment]
안녕하세요 @hyunwoongko,
위에서 하신 것처럼 `num_workers=1`로 설정하면 멀티스레딩을 사용하지 않게 됩니다.
혹시 위 에러가 발생한 kiwipiepy의 버전을 공유해주실 수 있으실까요?

**Comment by hyunwoongko** [comment]
'0.14.0' 입니다.

**Comment by bab2min** [comment]
@hyunwoongko 넵 감사합니다. 확인해보도록 하겠습니다~

**Comment by bab2min** [comment]
안녕하세요, @hyunwoongko 
2021년 M1 Pro (Monterey)에서 제보해주신 오류를 재현해보려고 시도했는데요, Python 3.7.3~3.10.6까지 전부 재현이 안되네요.
다만 유사한 멀티스레딩 관련 버그가 kiwipiepy 0.10.x에 있었고, https://github.com/bab2min/Kiwi/commit/c34c64e54e4c0f259b4982ddf11fc1a3e404ae25 에서 해결된 적이 있습니다.

혹시나 사용 중인 버전을 다시 한번 확인 부탁드리고, 만약 그래도 멀티스레딩 관련 버그가 계속 되시면
```python
from kiwipiepy import Kiwi

kiwi = Kiwi(num_workers=1)
[kiwi.tokenize(s) for s in ["아버지가방에들어가시다.", "아버지가방에들어가시다."]]
```
와 같이 강제로 `kiwi.tokenize`에 단일 text만 입력하여서 반드시 단일 스레드에서 동작하게 하는 방법을 쓰시는걸 권장드립니다.

**Comment by hyunwoongko** [comment]
답변 감사합니다!
