### ISSUE TITLE
단어의 토큰화 결과 문의

### ISSUE THREAD

**Issue by smbslt3** [bab2min/kiwipiepy#110]
안녕하세요

kiwi tokenizer를 알게 된 이후 kiwi를 주력으로 사용하고 있습니다.
최근 단어의 어근을 추출해서 비교해야될 일이 있어서 kiwi를 사용했는데, 다소 모호한 결과가 나와 문의드립니다.

```python
print( kiwi.tokenize('구원') )
print( kiwi.tokenize('구원하다') )
[Token(form='구', tag='NR', start=0, len=1), Token(form='원', tag='NNB', start=1, len=1)]
[Token(form='구원', tag='NNG', start=0, len=2), Token(form='하', tag='XSA', start=2, len=1), Token(form='다', tag='EF', start=3, len=1)]

print( kiwi.tokenize('그늘') )
print( kiwi.tokenize('나무그늘') )
[Token(form='그', tag='IC', start=0, len=1), Token(form='늘', tag='MAG', start=1, len=1)]
[Token(form='나무', tag='NNG', start=0, len=2),   Token(form='그늘', tag='NNG', start=2, len=2)]


print( kiwi.tokenize('고마워') )
print( kiwi.tokenize('고마움') )
print( kiwi.tokenize('고마워하다') )
[Token(form='고맙', tag='VA-I', start=0, len=3), Token(form='어', tag='EF', start=2, len=1)]
[Token(form='고마움', tag='NNG', start=0, len=3)]
[Token(form='고마워하', tag='VV', start=0, len=4), Token(form='다', tag='EF', start=4, len=1)]
```

문장을 토큰화 하는 것에 비해 단어 그 자체에 토크나이즈 함수를 걸면, 단어가 그대로 나오기보다는 쪼개어져서 다른 의미로 해석됩니다(`구원`, `그늘` 경우).
얼핏 봐도 꽤 많은 경우가 이렇게 잘못 쪼개어지는데 문장을 토크나이징 하는게 주 목적인 알고리즘상 어쩔 수 없는건가요?

그리고 `고맙-`의 어근이 일정하게 분리되지 않는 것을 확인했습니다.
이는 `고맙`, `고마움`, `고마워하-`라는 토큰이 각각 존재하기 때문에 그런건가요?
얼핏 생각해보면 `고마(고맙)+@`로 분리되어서 `고마워`, `고마움`, `고마워하다`가 모두 같은 토큰을 공유하고 있어야 할 것 같은데,
위 결과를 보시면 세 표현이 서로 관련이 없는 세 종류의 형태소로 분리가 되네요.

그럼 좋은 형태소 분석기 개발 및 운영해주셔서 감사합니다.
새해 복 많이 받으세요.

**Comment by bab2min** [comment]
안녕하세요 @smbslt3, 좋은 의견 주셔서 감사합니다!

첫번째 문제의 경우 말씀하신것처럼 언어 모델이 주로 문장을 모델링하도록 학습된 탓에 단어 하나가 입력되면 과하게 분절하는 문제가 있습니다. 단어 하나를 넣는 케이스는 고려하지 못했었는데, 다음 버전부터는 이런 경우도 고려하여 과분절되지 않도록 모델을 보완해보도록 하겠습니다.

두번째 문제는 분석기가 어느 수준까지 분석을 할 지에 관한 문제인데요, 이게 연구자마다(또 분석기마다) 분석 단위가 다르다보니 조금 중구난방인 문제가 있습니다. Kiwi의 경우 세종계획말뭉치와 모두의 말뭉치를 기반으로 개발되었는데요, 여기에서는 원칙상 표준국어대사전에 등재된 단어를 기준으로 형태소를 분절하고 있습니다. 사전을 확인해보시면 `고맙다`, `고마움`, `고마워하다`가 각각 등재되어 있는걸 볼 수 있는데요, 이 때문에 형태소 분석시에도 `고맙-`, `고마움`, `고마워하-`를 최소 단위로 쓰고 있는 것입니다. `좋아하다`, `뛰어가다`, `화려하다` 등과 같이 복합 단어인것처럼 보이지만 전체 단어가 통째로 사전에 등재된 사례가 꽤 있습니다.

근데 사실 이 형태소 등재 기준이 상당히 자의적이라서 이용자들이 기대하는 직관적인 결과랑 다른 경우가 자주 있는 것 같아요.  (심지어 말뭉치 구축 과정에서 같은 말뭉치 내에서도 같은 단어를 서로 다르게 태깅을 한 경우도 꽤 있구요.) 그래서 간단하게 처리하기는 조금 어려워보이지만, 데이터를 검수하면서 기준을 통일하거나 아니면 별도로 옵션을 주어 분석 수준을 사전 등재 기준으로 할지, 아니면 최소 단위까지 할지 이용자가 선택하게 하는 방향으로 개선하면 좋겠네요.
어떤 방향으로 개선할지는 조금 더 고민해보도록 하겠습니다. 다시 한 번 좋은 의견 제안해주셔서 감사합니다~

**Comment by smbslt3** [comment]
답변 감사합니다. 세종계획이나 사전부터 그렇게 분류를 하는거면 바꾸는게 쉽지는 않겠네요...
늘 한국어 자연어 처리를 위해 애써주셔서 감사합니다. 그럼 좋은 하루 되세요!
