### ISSUE TITLE
도커 이미지 실행 중 에러 문의

### ISSUE THREAD

**Issue by ByeongmokKim** [bab2min/kiwipiepy#114]
안녕하세요.

프로젝트 진행 중 인공지능 모델을 제작할 때 형태소 분석 기능이 필요해 kiwipiepy 라이브러리를 사용하고 있습니다.
kaggle 및 vscode 상에서는 정상 작동을 확인했습니다.

1. 로컬 개발 환경(Flask 웹 서버, Windows)에서는 키위 라이브러리 정상 설치 및 실행 가능
2.  Flask 웹 서버(로컬)에서 인공지능 모델의 정상적인 입/출력 확인
3.  Flask 웹 서버를 도커 허브에 올리기 위해, dockerfile 내에 이미지 빌드를 할 때 requirements.txt 파일에 kiwipiepy=0.14.1을 추가해서 빌드
4. Ec2 우분투 서버에 도커 이미지를 다운한 후, 컨테이너를 실행시키니 아래의 에러 발생

`Uncaughted c++ exception: cannot find the original morpheme 었/EP ai | Traceback (most recent call last):`

우분투 서버에 c++ 컴파일러(g++)가 존재하지 않아 해당 에러가 발생하는 것인지, 아니면 다른 문제로 인해 발생하는 에러인지 궁금합니다.

**Comment by bab2min** [comment]
@ByeongmokKim
안녕하세요, kiwi 파이썬 패키지는 크게 분석 코드를 제공하는 `kiwipiepy` 패키지와 분석에 필요한 모델을 제공하는 `kiwipiepy_model` 패키지로 구성되어 있습니다. 두 패키지가 모두 있어야 형태소 분석이 가능합니다. 그래서 `kiwipiepy`를 설치할 때 자기 버전에 알맞는 `kiwipiepy_model`을 설치하도록 되어 있는데요, `kiwipiepy==0.14.1` 버전 설치 시 무조건 `kiwipiepy_model` 최신 버전을 사용하도록 하는 버그가 있는걸로 확인되었습니다. 현재 최신 버전은 0.15.0이므로 kiwipiepy 설치시 0.14에서 호환불가능한 0.15을 가져오게 되구요 이 때문에 제보해주신 버그가 나타나게 된 것입니다.

해결 방법은 크게 2가지가 있겠습니다.
1. 해당 버그로부터 자유로운 `kiwipiepy==0.15.0` 버전을 사용한다.
2. requirements.txt 파일에서 `kiwipiepy==0.14.1` 위쪽에 `kiwipiepy_model==0.14.0`를 추가하여 pip가 무조건 동일한 버전을 설치하도록 강요한다.

개인적으로는 더 최신 버전을 사용하는 1번을 추천합니다만, 0.14.1 버전을 꼭 사용해야하는 경우 2번으로 해결하시면 되겠습니다.
감사합니다.

**Comment by ByeongmokKim** [comment]
0.15.0 버전 사용 후 해결됐습니다.
빠른 답장 감사합니다!
