### ISSUE TITLE
문장 분리 오류

### ISSUE THREAD

**Issue by deankim07** [bab2min/kiwipiepy#116]
다음과 같은 오류가 있습니다.
'~ 적법절차의 실질적인 내용을 침해하였는지 여부 등에 관하여 충분히 심리하지~' -> '~ 적법절차의 실질적인 내용을 침해하였는지', '여부 등에 관하여 충분히 심리하지~'

감사합니다.

**Comment by bab2min** [comment]
안녕하세요 @deankim07 님 오류 제보 감사합니다. 다음 언어 모델 업데이트 때에 반영하도록 하겠습니다.

**Comment by deankim07** [comment]
안녕하세요, 한 가지 더 제보하려고 합니다.
문장 중간에 있는 단어를 설명하는 괄호가 있고, 괄호안의 문장이 ~한다로 끝나는 경우에도 문장을 분리하는 현상이 있습니다.

'2023. 5. 10 주식회사 키위(이하 '회사'라 한다) 대표이사 XXX는 저녁을 직원들에게 사주었다.' 가  '2023. 5. 10 주식회사 키위(이하 '회사'라 한다)', '대표이사 XXX는 저녁을 직원들에게 사주었다.' 2개로 나누어 집니다.

감사합니다.
