### ISSUE TITLE
kiwipiepy 서버 권장 사양 문의드립니다.

### ISSUE THREAD

**Issue by ByeongmokKim** [bab2min/kiwipiepy#117]
aws ec2 서버에서 kiwi 라이브러리를 이용한 자연어 처리 분류 모델을 구동하려고 합니다.

현재 t2.micro (코어 1개, RAM 1기가) 사양으로 사용 중이며 형태소 분석을 실행하면 서버가 kill 되어버립니다.
로컬 flask 서버에서 테스트 할 때에는 문제가 없었기 때문에, 저희는 서버 사양을 원인으로 생각하고 있습니다.

권장하는 서버 사양이 궁금합니다.

**Comment by bab2min** [comment]
@ByeongmokKim 안녕하세요,
환경마다 조금씩 상이하지만 기본적으로 분석 모델을 로드하면 200~500MB 정도의 메모리가 들어갑니다. (만약에 `typos`를 이용한 오타 교정 기능까지 사용한다면 모델의 메모리 사용량만 1GB를 훌쩍 넘어가구요.)
그리고 분석 텍스트의 규모나 패턴에 따라 분석에 소요되는 메모리도 있을거구요. flask를 비롯한 다른 로직까지 고려한다면 여러모로 RAM 1GB로는 부족할것으로 보입니다.
최소 구동 사양은 정확히 모르겠지만, RAM은 적어도 2GB 이상, 넉넉하게는 4GB이 필요하지 않을까 싶습니다.

**Comment by ByeongmokKim** [comment]
빠른 답장 감사합니다!
