### ISSUE TITLE
안녕하세요 가 NNP 로 나와서요...

### ISSUE THREAD

**Issue by nowtoday** [bab2min/kiwipiepy#119]
안녕하세요 가 NNP 로 나와서요...
혹시나 해서 KiwiGUI 에서도 봤는데 마찬가지네요...
어디서 그런건가 찾아보니 default.dict 에 정의되어 있는 것 같은데... 

직접 파일을 수정해서 사용해야 하는걸까요?
사용자 단어를 추가하는 것은 사용중이지만 기본 형태소를 제거하는 방법은 못찾아서... 다른 방법이 있을까요???

**Comment by bab2min** [comment]
@nowtoday 앗, TV프로그램 때문에 NNP로 기본사전에 들어가 있나보네요... 이게 이런 종류의 고유명사 때문에 분석이 애매한 경우가 꽤 있거든요. 0.15.0버전부터 추가된 blocklist를 이용하면 특정 형태소가 분석 결과에 나오지 않도록 막을 수 있습니다.
```python
from kiwipiepy import Kiwi
kiwi = Kiwi()
kiwi.tokenize('안녕하세요')
# [Token(form='안녕하세요', tag='NNP', start=0, len=5)]

kiwi.tokenize('안녕하세요', blocklist=['안녕하세요/NNP'])
# [Token(form='안녕', tag='NNG', start=0, len=2), Token(form='하', tag='XSA', start=2, len=1), Token(form='세요', tag='EF', start=3, len=2)]
```
일단 임시 방편이겠지만 위처럼 blocklist를 사용하시는 걸 추천드립니다. 본질적인 해결법은 계속 고민해보도록 하겠습니다.

**Comment by bab2min** [comment]
@nowtoday 0.16.0에서 `안녕하세요` 분석 문제 해결되었습니다~
