### ISSUE TITLE
model_type = 'sbg' 관련 문의

### ISSUE THREAD

**Issue by KKang29** [bab2min/kiwipiepy#122]
안녕하세요, 먼저 좋은 라이브러리를 개발해주시고 공개해주셔서 너무 감사드립니다. 

형태소 분석기를 로드할 때, 모델을 'sbg'로 설정하였습니다.

이후 토크나이저를 통해서 '이 번호로 전화를 이따가 꼭 반드시 걸어.' 라는 문장을 분석하였는데 
'걷' 이라는 word가 VV-I로 잡혀서 나옵니다.

제 환경의 문제일 수도 있다고 판단하여 코랩에서도 돌려보니 동일하게 나옵니다.

버그인지 아닌지 판단이 안되어 이슈리포트로 남겨둡니다.

분석 코드는 아래에 첨부하겠습니다.
감사합니다.

from kiwipiepy import Kiwi
kiwi = Kiwi(model_type='sbg')
kiwi.tokenize('이 번호로 전화를 이따가 꼭 반드시 걸어.')

Token(form='이', tag='MM', start=0, len=1),
 Token(form='번호', tag='NNG', start=2, len=2),
 Token(form='로', tag='JKB', start=4, len=1),
 Token(form='전화', tag='NNG', start=6, len=2),
 Token(form='를', tag='JKO', start=8, len=1),
 Token(form='이따가', tag='MAG', start=10, len=3),
 Token(form='꼭', tag='MAG', start=14, len=1),
 Token(form='반드시', tag='MAG', start=16, len=3),
 Token(form='걷', tag='VV-I', start=20, len=1),
 Token(form='어', tag='EF', start=21, len=1),
 Token(form='.', tag='SF', start=22, len=1)]

**Comment by bab2min** [comment]
안녕하세요 @KKang29, 좋은 제보에 감사드립니다.
먼저, 데이터셋으로부터 유도된 확률을 기반으로 작동하는 모델 특성 상 항상 정확한 결과를 내지는 못한다는 점 말씀드립니다.
그래서 분석오류 자체는 버그로 판단하고 있지는 않는데요, 위의 예시는 이전 버전의 sbg 모델에서는 `걸/VV`로 바르게 분석을 해내는 예제였기 때문에 최신 버전의 sbg 모델이 어딘가 잘못 학습되었거나 학습 데이터가 부족했을지도 모르겠다는 생각이 드네요.
이에 대해서는 좀 더 조사해보도록 하겠습니다. 감사합니다.

**Comment by bab2min** [comment]
@KKang29 0.16.0 버전에서 해당 문제 해결되었습니다.
