### ISSUE TITLE
split_into_sents에 stopwords 인자 문의

### ISSUE THREAD

**Issue by uoneway** [bab2min/kiwipiepy#123]
안녕하세요.
정말 멋진 모듈 공유해주셔서 정말 감사합니다!

다름이 아니라 
문장분리와 tokenize를 동시에 하려고 split_into_sents를 봤습니다.
아직 여기에는 stopwords 인자가 없는듯 한데 맞을까요?

물론 별도로 할 수 있겠지만 약간 속도가 느려질것 같아 확인차 여쭤봅니다.

**Comment by bab2min** [comment]
안녕하세요 @uoneway ,
네, 문의해주신 것처럼 `split_into_sents`에는 `stopwords` 인자가 없습니다. 처음에 해당 메소드를 설계할때는 문장 분리를 주 목적으로 하다보니 `stopwords` 인자를 넣을 생각을 안 했었거든요. 그런데 종종 split_into_sents에서도 stopwords를 쓸 일이 있기도 한듯하고 tokenize와 인터페이스를 동일하게 통일하는 게 사용자 입장에서는 덜 혼란스러울테니, 다음 업데이트 때에 반영하도록 하겠습니다.
좋은 제안 감사합니다~
