### ISSUE TITLE
add_pre_analyzed_word 사용 시 인덱싱 오류

### ISSUE THREAD

**Issue by newdboy** [bab2min/kiwipiepy#127]
안녕하세요 너무 잘 쓰고 있습니다. 감사드립니다~!
Google colab 환경에서 버그로 추정되는 부분 발견하여 보고드립니다.
제가 add_pre_analyzed_word를 사용했는데, 시퀀스의 인덱스가 아래와 같이 잘못 산출되는 걸 발견했습니다.

>  ('격자', 'NNG', 21, 24),
>  ('판', 'NNG', 21, 24),

원래대로라면, 아래처럼 나와야 할텐데요.

> ('격자', 'NNG', 21, 23),
> ('판', 'NNG', 23, 24)

밑에 코드 첨부합니다.

```
# 형태소 분석 결과 추가 정의 (add_pre_analyzed_word)
kiwi = Kiwi(num_workers=4, model_type='sbg')  #, typos='basic'
kiwi.add_pre_analyzed_word('실세계', [('실','NNG'), ('세계', 'NNG')], 100)
kiwi.add_pre_analyzed_word('격자판', [('격자', 'NNG'), ('판','NNG')], 100)

def tokenizer_kiwi(sent, pre_spacing=False):  # [(형태소1, 품사1), (형태소2, 품사2), ...] 형태로 결과를 리턴
    if pre_spacing:
        sent = kiwi.space(sent, reset_whitespace=True)
    result = list(map(lambda x: (x[0], x[1], x[2], x[2]+x[3]), kiwi.tokenize(sent)))
    return result

tokenizer_kiwi("먼저 차량 주위 바닥에 바둑판 모양의 격자판을 펴 놓고 카메라로 촬영한다.")
```
# 결과
[('먼저', 'MAG', 0, 2),
 ('차량', 'NNG', 3, 5),
 ('주위', 'NNG', 6, 8),
 ('바닥', 'NNG', 9, 11),
 ('에', 'JKB', 11, 12),
 ('바둑판', 'NNG', 13, 16),
 ('모양', 'NNG', 17, 19),
 ('의', 'JKG', 19, 20),
 ('격자', 'NNG', 21, 24),
 ('판', 'NNG', 21, 24),
 ('을', 'JKO', 24, 25),
 ('펴', 'VV', 26, 27),
 ('어', 'EC', 26, 27),
 ('놓', 'VX', 28, 29),
 ('고', 'EC', 29, 30),
 ('카메라', 'NNG', 31, 34),
 ('로', 'JKB', 34, 35),
 ('촬영', 'NNG', 36, 38),
 ('하', 'XSV', 38, 39),
 ('ᆫ다', 'EF', 38, 40),
 ('.', 'SF', 40, 41)]

**Comment by bab2min** [comment]
안녕하세요 @newdboy ~ kiwipiepy에 관심가져주셔서 감사합니다.
현재 `add_pre_analyzed_word`는 자동적으로 분석 형태소의 위치 정보를 반영하지 않고 있어요. 그래서 이를 통해 등록된 단어는 위치 정보가 잘못 잡히게 됩니다.

일단 README에 있는 설명을 그대로 가져와보자면 다음과 같습니다.
```python
# 다음과 같이 add_pre_analyzed_word 메소드를 이용하여 이를 교정할 수 있습니다.
>>> kiwi.add_pre_analyzed_word('사겼대', ['사귀/VV', '었/EP', '대/EF'], -3)
True
# 그 뒤 동일한 문장을 다시 분석해보면 결과가 바뀐 것을 확인할 수 있습니다.
>>> kiwi.tokenize('걔네 둘이 사겼대')
[Token(form='걔', tag='NP', start=0, len=1), 
 Token(form='네', tag='XSN', start=1, len=1), 
 Token(form='둘', tag='NR', start=3, len=1), 
 Token(form='이', tag='JKS', start=4, len=1), 
 Token(form='사귀', tag='VV', start=6, len=3), 
 Token(form='었', tag='EP', start=6, len=3), 
 Token(form='대', tag='EF', start=6, len=3)]
# 단, 사귀/VV, 었/EP, 대/EF의 시작위치가 모두 6, 길이가 모두 3으로 잘못 잡히는 문제가 보입니다.
# 이를 고치기 위해서는 add_pre_analyzed_word 시 각 형태소의 위치정보도 함께 입력해주어야합니다.
>>> kiwi = Kiwi()
>>> kiwi.add_pre_analyzed_word('사겼대', [('사귀', 'VV', 0, 2), ('었', 'EP', 1, 2), ('대', 'EF', 2, 3)], -3)
True
>>> kiwi.tokenize('걔네 둘이 사겼대')
[Token(form='걔', tag='NP', start=0, len=1), 
 Token(form='네', tag='XSN', start=1, len=1), 
 Token(form='둘', tag='NR', start=3, len=1), 
 Token(form='이', tag='JKS', start=4, len=1), 
 Token(form='사귀', tag='VV', start=6, len=2, 
 Token(form='었', tag='EP', start=7 len=1), 
 Token(form='대', tag='EF', start=8 len=1)]
```

질문하신 예시에서는 다음처럼 시작 위치와 끝 위치를 추가로 적어주는 방향으로 수정하면 되겠습니다.
```python
kiwi.add_pre_analyzed_word('실세계', [('실','NNG', 0, 1), ('세계', 'NNG', 1, 3)], 100)
kiwi.add_pre_analyzed_word('격자판', [('격자', 'NNG', 0, 2), ('판','NNG', 2, 3)], 100)
```

원래 `add_pre_analyzed_word` 메소드는 `사겼대`와 같이 불규칙한 형태의 분석결과를 수동으로 입력하는 목적으로 설계되었기 때문에 형태소 각각의 위치 정보를 직접 입력하도록 되어 있었는데요, 제보해주신 것과 같은 상황에서는 kiwipiepy가 간단하게 각 형태소들의 시작지점/끝지점을 스스로 파악할 수 있어 보이니 이 경우에는 자동으로 위치 정보를 반영하도록 개선하도록 하겠습니다~
좋은 제보 감사합니다.

**Comment by newdboy** [comment]
아 그렇군요 너무 자세한 답변 감사드립니다!! 너무너무요
