### ISSUE TITLE
dataclasses 관련 에러

### ISSUE THREAD

**Issue by GukjinHan** [bab2min/kiwipiepy#128]
안녕하세요
이 모듈 덕분에 python에서 kiwi tokneinzer를 잘 사용하고 있습니다. 감사합니다.

한가지 문의가 있어서 찾아왔습니다.

- python version : 3.9.11
- kiwipiepy : 0.15.2
- platform : amd64 (amazon linux 2)

dataclasses 모듈 관련해서 python 3.7 이상의 버전에서는 아래와 같은 에러가 발생하는 것 같습니다.
```
AttributeError: module 'typing' has no attribute '_ClassVar'
```

이와 관련해서 다른 곳(https://github.com/huggingface/transformers/issues/8638) 에서는 python 버전이 3.7 이상인 경우 dataclasses를 requirements에 포함시키지 않는 걸로 패치하고 있습니다.
혹시 확인 해주실 수 있을까요?

**Comment by bab2min** [comment]
안녕하세요 @GukjinHan 
버그 제보에 감사드립니다~ 공유해주신 내용 참조하여 다음 업데이트에 반영하도록 하겠습니다!!
