### ISSUE TITLE
서브워드 토크나이저 학습(SwTokenizer) 데이터 문의

### ISSUE THREAD

**Issue by ByungjunKim** [bab2min/kiwipiepy#132]
안녕하세요 만들어주신 서브워드 토크나이저를 정말 잘 쓰고 있습니다.

이슈라기 보다는 몇 가지 궁금한 점이 있고, 이 글이 나중에 다른 분들께도 도움이 될 수 있다고 생각해 남겨둡니다.

1. 서브워드 토크나이저 학습 데이터 형태 추천
현재는 list of string 형태로 리스트에 문서를 담아서 학습을 하고 있는데요.
이 문서가 기사라서 적으면 5문장 많으면 수십문장이 들어가있습니다.
혹시 단위를 문서가 아니라 문장으로 쪼개서 list of string을 만든 후 학습을 하면 토크나이저의 정확도가 더 좋아질까요?
현재 학습 데이터가 근대 한국어 텍스트인지라 국한문 혼용체에대가 띄어쓰기가 없는 상태입니다.
따라서 서브워드 학습을 할때 이전 문장까지도 같이 들어가서 학습을 하게되는 것이 걱정되긴합니다.

2. 위 질문과 같이해서 서브워드 학습시에 자동으로 문장을 분리해서 학습을 현재 진행하는지 궁금합니다.
그렇다면 1번질문에서 나온 문장을 분리해서 학습해주는 일은 굳이할 필요가 없을 듯해서요.

좋은 패키니 만들어주셔서 감사합니다.

김병준 드림.

**Comment by bab2min** [comment]
안녕하세요 @ByungjunKim 
먼저 좋은 질문 남겨주심에 감사드립니다.

문장 분리를 무엇으로 하는지에 따라 굳이 수행할 필요가 없을수도 있을수도 있습니다.
1. 문장 분리를 Kiwi로 수행하는 경우
이 경우라면 굳이 문장 분리를 수행할 필요가 없습니다. 어차피 Kiwi subword tokenizer학습 과정에서 자체적으로 형태소 분석을 통해 종결 어미 등을 탐지하므로 종결 어미 뒤에 다른 글자가 따라붙는다고 해도 둘이 붙어서 학습에 투입되지 않기 때문입니다. 
2. 문장 분리를 수작업 혹은 다른 방법으로 수행하는 경우
이 경우라면 수행하는게 좋을수도 나쁠수도 있습니다. 문장 분리 정확도가 Kiwi 것보다 좋다면 수행하는게 좋을 것이구요 그게 아니라면 수행하면 오히려 노이즈가 들어갈테니 악영향을 미칠것으로 예상됩니다.

감사합니다!

**Comment by ByungjunKim** [comment]
친절한 답변 정말 감사합니다. 이미 kiwi로 학습할때 문장분리를 고려하는 군요. 정말 좋은 서브워드 학습기능입니다.
계속 학습하면서 더 좋은 기능제안이나 문의사항 남기겠습니다.
