### ISSUE TITLE
시작 위치 및 길이가 제대로 분석되지 않습니다.

### ISSUE THREAD

**Issue by kipa00** [bab2min/kiwipiepy#15]
안녕하세요, 먼저 좋은 프로그램 잘 쓰고 있습니다. 감사합니다.

```
$ python3 -m kiwipiepy
>>되었다
([('되', 'VV', 0, 1), ('었', 'EP', 1, 1), ('다', 'EC', 2, 1)], -12.622314453125)
>>됐다
([('되', 'VV', 1, 0), ('었', 'EP', 0, 1), ('다', 'EC', 1, 1)], -12.622314453125)
>>하였다
([('하', 'VV', 2, 0), ('었', 'EP', 1, 1), ('다', 'EC', 2, 1)], -16.640380859375)
>>했다
([('하', 'VV', 1, 0), ('었', 'EP', 0, 1), ('다', 'EC', 1, 1)], -16.640380859375)
>>
```
준말과 관련된 "시작 위치"가 조금 이상하게 동작하는 것 같습니다.

"시작 위치"를 "끝 위치에서 단어의 길이를 뺀 값"으로 생각하면 `됐다`와 `했다`의 경우는 이해가 갑니다만, `되었다`에 비해 여전히 `하였다`가 작동하는 방식은 잘 이해가 가지 않습니다.

**Comment by bab2min** [comment]
안녕하세요, 먼저 해당 내용을 제보해주셔서 감사합니다.
확인해보니 '됐'이나 '했'처럼 둘 이상의 형태소가 결합하여 축약된 경우 시작위치 및 길이 계산이 부정확하게 되는 문제가 있는 걸로 보입니다.
구현시 목표대로라면 '됐'의 분석결과에서 '되'와 '었' 모두 0번 인덱스에서 시작하고, 길이는 1이 되는게 맞습니다. 해당 버그는 다음 패치에서 수정하도록 하겠습니다.
다시 한 번 감사합니다

**Comment by EedoCelsius** [comment]
좋은 프로그램, 그리고 꾸준한 패치 정말 감사합니다!
새로운 릴리스 알람이 올라올 때 마다 해당 버그패치에 대해 확인해보러 매번 뛰어오는 사람입니다.

단순한 숫자 오타로 인한 버그인지 계산 로직 자체를 뜯어 고쳐야 하는 부분인지 궁금하네요
후자의 경우라면 현재 반환되는 결과물에서 오차를 줄이는 코드라도 따로 작성해서라도 사용하려고 하나
그저 축약형을 토큰화하는 섹션에 숫자적 오타가 있어 나타나는 버그일 수도 있는데 괜히 힘빼가면서 정확하지도 않은 결과물을 만드는건 아닌가 싶어 아직까지는 패치만 기다리고 있습니다.

**Comment by bab2min** [comment]
@kipa00, @EedoCelsius
형태소 분석 사전 내부 구조와 복잡하게 얽혀있는 문제라서 예상보다 버그 수정이 많이 늦어졌네요.
0.11.0 버전에서 해당 버그는 수정되었습니다. 감사합니다.
