### ISSUE TITLE
사용자 사전 사용 버그

### ISSUE THREAD

**Issue by WooheonHong** [bab2min/kiwipiepy#150]
다음 코드를 실행시킬 때 

```python
from kiwipiepy import Kiwi

kiwi = Kiwi()
kiwi.load_user_dictionary("???.txt")
```

텍스트 이름에 관계없이 `load_user_dictionary`메소드를 사용하면 바로 세션이 다운됩니다.
vscode, 코랩.. 상관없이 다운되네요

**Comment by ByungjunKim** [comment]
[제보] 제가 쓰다가 보니 사용자 사전 파일에 띄어쓰기가 있는 단어를 넣은경우 뻗어버리네요.

**Comment by bab2min** [comment]
0.17.0 버전에서 잘못된 입력에 대해 커널이 강제 종료되는 대신 `ValueError`를 던지도록 수정되었습니다.
