### ISSUE TITLE
Kiwi 0.16.1 반영

### ISSUE THREAD

**Issue by tree1891** [bab2min/kiwipiepy#157]
Kiwi 0.16.1 은 언제 반영되는지요?

**Comment by bab2min** [comment]
안녕하세요~
Kiwi 0.16.1의 기능들은 이미 [kiwipiepy 0.16.1](https://github.com/bab2min/kiwipiepy/releases/tag/v0.16.1)에 반영되어 있습니다~

**Comment by tree1891** [comment]
릴리즈 날짜가 다른데요.
Kiwi 0.16.1 은 올해로 되어 있습니다.

**Comment by bab2min** [comment]
아 그건 KiwiJava쪽 distribution workflow가 제대로 작동하지 않아서 release tag를 올해 초에 수정했기 때문입니다.
0.16.1 배포는 작년 11월에 있었고 그게 반영된게 kiwipiepy 0.16.1입니다~
