### ISSUE TITLE
기본 가이드 따라 진행시 TypeError: 'num_thread' is an invalid keyword 

### ISSUE THREAD

**Issue by Beomi** [bab2min/kiwipiepy#16]
작업환경: Google Colab 2020.07.06
Kiwipiepy 버전: kiwipiepy-0.8.1 from Pypi

![image](https://user-images.githubusercontent.com/11323660/86549536-dd6c5080-bf7a-11ea-8b9f-20c85c9fc1bd.png)

위 이미지와 동일한 에러가 납니다.
(참고로 kwargs 없이는 잘 됩니다. workers 부분에서 문제가 있는듯 합니다.)

코랩링크: https://colab.research.google.com/drive/1UcEP6peqGEcRdknfFN0BuJQBskGmIQMT?usp=sharing

**Comment by bab2min** [comment]
안녕하세요, 예리한 제보 감사합니다. 
num_thread 키워드 이름이 num_workers로 변경되었었는데, documentation 업데이트가 안 되어있었네요. documentation 수정했습니다. 
감사합니다.
