### ISSUE TITLE
README.md 오타 발견

### ISSUE THREAD

**Issue by ByungjunKim** [bab2min/kiwipiepy#17]
안녕하세요. README.md 파일에 사소한 오타가 있어 남겨봅니다. 늘 감사한 마음뿐입니다.
미동록 -> 미등록
입니다.
이상입니다.

https://github.com/bab2min/kiwipiepy#%EC%BD%94%ED%8D%BC%EC%8A%A4%EB%A1%9C%EB%B6%80%ED%84%B0-%EB%AF%B8%EB%8F%99%EB%A1%9D-%EB%8B%A8%EC%96%B4-%EC%B6%94%EC%B6%9C

**Comment by bab2min** [comment]
앗 오타 발견에 감사드립니다! 수정할게요~
