### ISSUE TITLE
Match.JOIN_AFFIX 이후 join 시 문제

### ISSUE THREAD

**Issue by comchobo** [bab2min/kiwipiepy#176]
안녕하세요, 키위 토크나이저를 사용하며 여러 텍스트 분석을 시도해보고 있습니다. 좋은 라이브러리 감사합니다.
다만 match_options에 어떤 값을 넣는지에 따라 갑작스럽게 커널이 죽는 등 현상이 발생해서 이슈를 작성합니다.

kiwipiepy==0.18.1 을 사용하고 있으며,코드는 다음과 같습니다.

```python
from kiwipiepy import Kiwi, Match
kiwi = Kiwi(model_type="knlm", num_workers=1) # model_type='sbg' 혹은 num_workers를 변경해도 동일 에러 발생

parsed_tag = kiwi.tokenize(tag, match_options=Match.JOIN_AFFIX)
parsed_tag = [x for x in parsed_tag
    if x.tag.startswith("NN") or x.tag in ["SL", "SN"]]
after_tag = kiwi.join(parsed_tag)
```

kiwi.join을 수행할 때 커널이 아예 죽어버려서 어떤 점이 문제인지 잘 모르겠는데, 필요한 자료가 있으시다면 제공드리겠습니다.
감사합니다.

**Comment by bab2min** [comment]
안녕하세요 @comchobo 
제보해주신 것처럼 JOIN_AFFIX 등의 옵션을 주고 분석한 결과를 다시 합칠 때 C++단에서 크래시가 발생하는 현상을 확인하였습니다.
빠른 시일 내에 수정하여 패치를 올리도록 할게요! 오류 제보해주셔서 감사합니다~!

**Comment by bab2min** [comment]
@comchobo 해당 문제는 0.19.0버전에서 해결되었습니다.
