### ISSUE TITLE
[Question] Kiwi 의 사전 품사태그

### ISSUE THREAD

**Issue by SHwan93** [bab2min/kiwipiepy#18]
사용자 사전을 구축하려고 합니다.
txt 파일에 포맷을 설명해놓으셨는데 어떤 품사태그들을 사용하는지 정리해놓은 자료가 있을까요?

그리고 해당 라이브러리는 불용어 (stop word) 사전을 지원할 생각이 있나요?

**Comment by SHwan93** [comment]
세종 품사 사용하시는것 확인하였습니다

불용어 부분만 답변 부탁드려요

**Comment by bab2min** [comment]
좋은 지적에 감사드립니다. 생각해보니 사용중인 품사태그를 정리해둔 문서가 없었었네요... Kiwi 품사 태그를 정리하여 다음 링크에 추가해두었습니다. 
https://github.com/bab2min/kiwipiepy#%ED%92%88%EC%82%AC-%ED%83%9C%EA%B7%B8

또한 불용어에 대해서는 사실 애매한 부분이 있습니다. 범용적으로 쓰일만한 불용어가 있으면 좋겠지만, 분석 텍스트나 사용 목적에 따라 불용어가 크게 달라지기 때문에 형태소 분석기 라이브러리 차원에서 불용어를 지원하는게 맞는지 고민 중에 있습니다.

**Comment by SHwan93** [comment]
제가 생각해도 불용어기능은 후순위가 맞는것같습니다. 유틸성 기능이니까요

이 프로젝트는 분석이라는 본질에 집중하고 에너지 쏟는게 긍정적일것 같습니다.
감사하고 응원합니다 ^^
