### ISSUE TITLE
사용자 문자 등록시 NNP, NNG에 우선 순위가 따로 있나요??

### ISSUE THREAD

**Issue by nowtoday** [bab2min/kiwipiepy#182]
기본에서는 고혈압이라는 단어가 [고/XPN + 혈압/NNG] 으로 나뉘길래
사용자 단어로 고혈압을 등록해서 사용해봤는데 이상한 점이 있어서요...
NNP로 등록할 때와 NNG로 등록할 때 다르게 나와서 문의드립니다.

NNG로 등록시
[...
  Token(form='고혈압', tag='NNG', start=49, len=3),
...
  Token(form='고혈압', tag='NNG', start=80, len=3),
...
  Token(form='고혈압', tag='NNG', start=122, len=3),
...]

NNP로 등록시
 [...
  Token(form='고혈압', tag='NNP', start=49, len=3),
...
  Token(form='고혈압', tag='NNP', start=80, len=3),
...
  Token(form='고', tag='XPN', start=122, len=1),
  Token(form='혈압', tag='NNG', start=123, len=2),
...]

샘플은 아래 텍스트로 작업했을 때처럼 일정하지가 않아서요...
(긴 문장을 테스트 해봤는데 그 중에서도 아래와 같이 특수문자가 들어있는 줄에서 반복적으로 발생하는 듯해서..)

#############################################
from kiwipiepy import Kiwi

text = '''
대부분 초기에는 증상이 나타나지 않기 때문에 조심히 살펴보아야 합니다.

✔️ 일차성 고혈압 - 원인 질환이 명확하지 않는 경우
✔️ 이차성 고혈압 - 명원한 원인 질환에 의해 발생하는 경우

평소 잘못된 생활습관은 고혈압 발생 가능성이 높은데요. 이러한 생활수칙에 흡연을 하거나 음주, 운동부족, 비만, 불규칙한 생활습관으로 발생하게 됩니다.
'''

kiwi_nng = Kiwi()
kiwi_nnp = Kiwi()

kiwi_nnp.add_user_word('고혈압') # 'NNP'
kiwi_nnp_add = kiwi_nnp.tokenize(text)

kiwi_nng.add_user_word('고혈압', 'NNG')
kiwi_nng_add = kiwi_nng.tokenize(text)

[token for token in kiwi_nng_add if token.tag.startswith('N') or token.tag.startswith('XPN') ], [token for token in kiwi_nnp_add if token.tag.startswith('N')  or token.tag.startswith('XPN') ]

**Comment by bab2min** [comment]
안녕하세요 @nowtoday 
Kiwi 내부의 언어모델에 따라서 NNG가 올 확률과 NNP가 올 확률이 서로 다르게 계산됩니다. 그래서 같은 형태라도 주변 맥락에 따라 새로 등록한 NNG 단어(혹은 NNP)로 분석이 될 수도 안 될 수도 있습니다.
그래서 고혈압이 항상 NNG (혹은 NNP)로 분석되길 원하신다면 add_user_word시에 user_score를 0보다 큰 값으로 주어서 해당 단어의 우선순위를 높게 지정하는게 좋습니다.
```python
kiwi.add_user_word('고혈압', 'NNG', 10) # 혹은 NNP
```

**Comment by nowtoday** [comment]
감사합니다... 프로그램 작업할 때 user_score를 잘 조절해서 사용해야겠네요...
