### ISSUE TITLE
띄어쓰기 오타 교정 문의드립니다.

### ISSUE THREAD

**Issue by SsoYeon-kim** [bab2min/kiwipiepy#187]
안녕하세요! 띄어쓰기 버그를 신속히 해결해 주셔서 정말 감사드립니다. 덕분에 유용하게 잘 활용하고 있습니다. 
사용 중에 오타 교정 관련하여 문의드릴 사항이 있어서 이렇게 이슈 남깁니다.

"잡는게 아님" → "잡는 것 아님"
"때문일겁니다" → "때문일 거니다"

<img width="494" alt="스크린샷 2024-10-31 오후 4 36 08" src="https://github.com/user-attachments/assets/441929fb-bbef-4dd8-9145-f0a3170fd76a">

None
잡는 것 아님
[([Token(form='잡', tag='VV-R', start=0, len=1), Token(form='는', tag='ETM', start=1, len=1), Token(form='것', tag='NNB', start=2, len=1), Token(form='이', tag='JKC', start=2, len=1), Token(form='아니', tag='VCN', start=4, len=2), Token(form='ᆷ', tag='EF', start=5, len=1)], -25.048259735107422)]
때문일 거니다
[([Token(form='때문', tag='NNB', start=0, len=2), Token(form='이', tag='VCP', start=2, len=1), Token(form='ᆯ', tag='ETM', start=2, len=1), Token(form='거', tag='NNB', start=3, len=1), Token(form='이', tag='VCP', start=3, len=1), Token(form='ᆸ니다', tag='EF', start=3, len=3)], -25.534648895263672)]

원문 그대로 띄어쓰기를 사용하고 싶은데
Kiwi 생성 후 typos가 None임에도 space()사용 시 오타 교정이 default인지 토크나이저 설정 등 다른 부분에서 문제가 발생하는 것인지 문의드립니다.

감사합니다!

**Comment by bab2min** [comment]
안녕하세요 @SsoYeon-kim 
이전에 제보해주셨던 버그를 수정하는 과정에서 발생한 사이드이펙트로 확인되었습니다. 추후 있을 0.20.1버전에서는 이 부분 패치한것까지 반영하도록 하겠습니다. 감사합니다~

**Comment by bab2min** [comment]
@SsoYeon-kim 버그 수정된 0.20.1버전 배포 완료되었습니다~
