### ISSUE TITLE
띄어쓰기 버그 문의드립니다.

### ISSUE THREAD

**Issue by SsoYeon-kim** [bab2min/kiwipiepy#189]
안녕하세요! 0.20.1 버전 업데이트에  감사드립니다. 덕분에 잘 사용하고 있습니다.
최근 업데이트 이후 한 가지 버그를 발견한 것 같아 이슈 남깁니다.

<img width="526" alt="스크린샷 2024-11-20 오전 9 22 53" src="https://github.com/user-attachments/assets/83ef78fd-0e71-43fc-bc3c-b472235853f5">

정확한 규칙은 모르겠지만
'⃝⃝ + 숫자 + 무료' 로 들어올 때 숫자가 앞 글자로 변환되어 분석되고 있습니다.

확인부탁드립니다. 감사합니다 :) !!

**Comment by bab2min** [comment]
@SsoYeon-kim 버그 제보에 감사드립니다!
확인 결과, 숫자나 URL등의 태그 패턴이 특정 환경에서 잘못 분석되는 오류가 있었습니다.
조금 전에 해당 버그를 수정하였고, 이 패치가 반영된 0.20.2를 배포 완료했습니다!
