### ISSUE TITLE
[Question] 기본 말뭉치 사전

### ISSUE THREAD

**Issue by SHwan93** [bab2min/kiwipiepy#19]
이 프로젝트는 현재 기존의 타 말뭉치 사전을 이용하는것이 아닌 Kiwi만의 사전을 구축하여 신조어에 대응하고 있나요?

이 질문을 하는 이유는, 분석 전 단어 추출을 통해서 신조어 및 사전에 없는 단어를 추출하는것도 있지만
만약 맞다면, 사용자가 패키지 업데이트를 자주 해주는것이 유리하게 작용하는지 궁금해서 입니다.

**Comment by bab2min** [comment]
말뭉치와 사전을 섞어서 사용하셨는데요, Kiwi에서 말뭉치와 사전의 역할은 각각 분리되어있습니다.
먼저 말뭉치의 경우, 세종계획 말뭉치를 사용하고 있구요, 말뭉치는 형태소 분석 모델을 학습하는데에 사용됩니다. 즉, 예를 들어 `먹/VV` 다음에는 `어/EP`가 등장할 확률이 높고, `뛰/VV`가 등장할 확률은 낮다는 걸 학습하기 위해 쓰이는 식입니다.
반면 사전은 특정 글자 배열이 어떤 형태소로 분석되어야하는지를 저장하기 위해 사용됩니다. 예를 들어 `수학능력시험`은 `수학능력시험/NNG`로 분석되어야한다는 걸 사전에 저장하는 것이죠. Kiwi의 기본 사전은 위키백과와 나무위키의 표제어를 바탕으로 작성되었습니다.

업데이트에 관해서 여쭤보셨는데요 Kiwi의 기본 사전은 위키백과와 나무위키의 표제어를 바탕으로 비정기적으로 업데이트되는 반면, 모델 학습에 쓰인 말뭉치는 거의 변하지 않습니다. 즉, 패키지 버전이 변할때 사전만 업데이트되고, 새로 추가되는 단어들은 위키백과 및 나무위키 표제어에 새로 등재된 단어들뿐입니다. (단, 패키지 버전이 크게 업데이트되는 경우 분석 알고리즘이나 말뭉치 학습 방법이 변경될 수 있기 때문에 이 경우는 예외로 치겠습니다.)

최종적으로 본 질문에 대답드리자면, 분석 대상 텍스트에 따라 업데이트의 효용성은 크게 달라질 수 있으나, 패키지 업데이트에 의존하기보다는 대상 텍스트에 맞춰 사용자 사전을 구축하는게 일반적으로 더 효과가 좋습니다. 단, 분석 알고리즘이 업그레이드되는 경우(업데이트 내역에 변동 내역이 표시됩니다.)는 업데이트하시길 권장합니다.

**Comment by SHwan93** [comment]
말뭉치와 사전의 개념을 한번 설명해주셔서 수월하게 글을 읽을 수 있었습니다 감사합니다 :)

네 사용자 사전 구축하며 프로젝트 업데이트내용을 확인하겠습니다
