### ISSUE TITLE
python 3.7에서 IOhandler에 오류가 뜹니다.

### ISSUE THREAD

**Issue by DrinkingMilktea** [bab2min/kiwipiepy#2]
아니콘다 python3.7버전에서 사용하려고 했습니다
예제 맨 밑의 IOhandler클래스를 그대로 가져다 썼는데
if id == 0:
  self.input.seek(0)   <--여기서 오류가 납니다.
파이썬 3.6버전으로 하니 다시 잘 동작합니다.
확인부탁드려요

**Comment by bab2min** [comment]
오류 제보 감사합니다!
해당 문제는 argument 파싱 부분에서 부적절하게 에러처리를 해서 발생한 것이었습니다. 문제를 해결한 0.7.2버전을 새로 배포하였으니 확인부탁드립니다.
