### ISSUE TITLE
[Question] load_user_dictionary 사용

### ISSUE THREAD

**Issue by SHwan93** [bab2min/kiwipiepy#20]
load_user_dictionary의 txt 파일에서 
(단어1 [탭문자] 품사태그 [탭문자] 단어점수)

1. 품사태그를 입력하지 않을시 기본으로 적용되는 품사태그가 있나요?
2. 단어점수의 범위가 있나요?

**Comment by bab2min** [comment]
품사태그는 생략할 수 없습니다. 만약 품사태그를 입력하지 않은 경우 해당 엔트리는 무효한것으로 판단되어 무시됩니다.
단어 점수의 범위 제한은 없습니다. 다만 일반적으로 최종 스코어가 단어당 -10 내외로 나오므로, -10~10 정도의 값이 유효할 것으로 보입니다.
https://bab2min.github.io/kiwipiepy/v0.8.0/kr/#_2
사용자 단어 점수에 대해서는 위 링크에 좀 더 상세한 설명이 있으니 살펴보시면 도움이 될거 같아요.

**Comment by SHwan93** [comment]
답변 감사합니다
