### ISSUE TITLE
[Error] kiwi::KiwiUnicodeException

### ISSUE THREAD

**Issue by SHwan93** [bab2min/kiwipiepy#21]
#바둑#장기#오목 귀요미#보드판🐥\n#어린이임블리의 놀이였는데, 이제는 가물갸물🙄모르겠\n장이요~멍이요~ㅎㅎㅎ다시 한 번 재미를 붙여 보까ㅎ\n할 일이 태산인데😭, 하고 싶은건 무궁무진🤦\u200d♀️ 큰 일이다 #바둑#장기#오목 귀요미#보드판🐥\n#어린이임블리의 놀이였는데, 이제는 가물갸물🙄모르겠\n장이요~멍이요~ㅎㅎㅎ다시 한 번 재미를 붙여 보까ㅎ\n할 일이 태산인데😭, 하고 싶은건 무궁무진🤦\u200d♀️ 큰 일이다

위의 문장의 분석 중 에러 발생합니다
libc++abi.dylib: terminating with uncaught exception of type kiwi::KiwiUnicodeException: unpaired surrogate

원문: https://www.instagram.com/p/CFgnSIXlgx4/

**Comment by bab2min** [comment]
오류 제보 감사합니다. 
emoji 분석 과정에서 문제가 발생하는거 같은데, 다음 업데이트에서 수정내역 반영하도록 할게요~!

**Comment by SHwan93** [comment]
춥다...집콕 시작​​​​​​​​#아침#무스비                                          아침으로 무스비를 거하게 먹고​​#후식#올리브빵#카페라떼                                          남편이 스타벅스 리저브에거 사온 올리브 빵을또 먹었네요​​​​​​​                    사실 여기서 혼자 장보기는 나에게 뭔가도전과 같은거​계산도 핸드폰으로 하고 뭐가 문제인가 싶지만난 뭐든 혼자하는건 겁난다​​이날은 다 좋았는데무게, 양 조절 실패로​몇번이나 쉬면서 집으로🤪​​​​​​​#운동                   카도오픈샌드위치#패션푸르츠#abc쥬스                                          아침에 밥 먹었으니 저녁은 샌디치​사실은 빵사온거 빨리 먹고파서빵수니🥖​​​​​#석류                    한국에선 잘 안먹던 과일인데여기선 열심히 먹고 있는 석류​여말랭이피클, 호두과자, 석류        ​​​​​​​#비빔밥#부추전                               나물반찬이 많아서 간만에 바빔밥근데 너무 과하게 많이 먹었....​​​​#후식#마카롱#아이스아메리카노                                          그래놓고 또 후             그래도 나름 꾸준히 운동중사실 유산소 조금, 홈트 조금이지만​운동 세상 싫어하던 나에겐아주 큰 발전​​​​​​​#호박마스크                                          귀여운 딸학교에서 만들었다며버스에서부터 마스크를 쓰고온...​히히​나                    저녁은 간단히하지만 고칼로리​​                    후식으로 석류까지 알차게 냠냠​​​​​​​​​#아침#소떡소떡                    아침부터 소떡소떡을 해먹습니다​☺️​​​​​​​#학습지                               딸 영어 학습지                 이날 학교 일정이 런치 먹고 일찍 하교였는데​요즘 너무 춥고사실...엄마 요즘 심심해...그래서 애들 학교 안보내고엄마랑 놀아달라고 부탁했다​학교 가겠다는 어린이들 꼬시려고케이크 만들기, 영화 관람으로 딜...​그래서 간만에 케이                                    초코머핀 믹스 였는데머핀 만들기는 번거로워서 그냥 한판으로 구워서 케이크로​마카롱과 함께 먹으니참 맛있었어요✌​​​​​​#저녁식사#월남쌈#수박쥬스                               요즘 정말 너무 먹는 것 같아서#어린이도시락             유부초밥, 치킨너겟, 오이피클, 패션푸르츠, 유산균음료        ​​​​​​​#스타벅스#크리스마스컵                                          스타벅스컵이 크리스마스 패키지로 바뀌었다고...​​​​​​#국제택배#우체국택배      하다보니뭔가 또 엄청 오래걸린기분​​                    꼭 부탁하지 않아도젤리며 이런저런 간식, 애들 장난감, 옷 등꼭 껴서 보내주는 시누이​진짜 천사.......사랑하는 시누이다 심지어 이건 뭔지 모르겠는데넘 맛이라 아껴먹고 이뜸​​            자된 기분❤️​​​​​​#도시락#런치박스             토마토펜네파스타, 오이피클, 방울토마토, 누룽지, 약과                   ​​​​​​​​​​​#아침#크로와상버섯샌드위치#노란수박#옥수수#카페라떼                                          냉털메뉴였는데 이뻐서 샀는데나름 유명한 브랜드에 법랑재질이었...​​중국어 몰라서 쇼핑을 해도 이런식 ㅋㅋ와봐야 안다여튼 법랑 재질에 가벼워서애들 컵으로도 괜찮을 것 같아서하나 더 주문했다​​​#할머니선물#고모선물                                      친정고...​엄마도 아빠도 안하는 주식을 딸이 먼저 샀다​덤으로 고모가 준 용돈은 기부까지❤️​​남은 오만원은 엄마 쓸께^^^^^^^^^​​​​​​​#팬드리                                          허접하지만 우리집 팬트리(?)​택배온거 싹 정리하고 나니세상뿌듯​ 오고있는 요즘​​​​​​​#하교                                          어린이들 하교길​나는 육출🧡​​​​​​​#저녁식사                    대충 차려먹어도이만큼​난 먹는데는 대충이 없다보다​​엄청 가지가지네​​​​​​​​#감성카페#가족출동                                                                                                                                                가족과 함께 카페 출동​오픈시간에 맞춰가서창가자리 사수​​심지어 이날은 디져트도 시켰는데마카롱 맛집맛있어​​​​​​#저녁#꿔바로우#마라탕#마라샹궈#칭따오맥주                                          저녁은 간만에 세트메뉴🧡🤎​말해뭐해​​​​​​​​#일요일아침#빵식                    간단히 아침 먹고​​​#날씨굿                    난 마사지남편과 아이들                               남편이랑 애들이 장보고난 마사지받고 합류해메트로​우리집 과소비 요인인 곳(아닌가^^^;타오바온가)​​​​​​#점저#떡볶이#부라타치즈떡볶이                                                     추억의 국민학교 치즈 떡먹어지길래같이 먹어보았는데...​떡볶이는 기본 떡볶이가 제일 맛있는걸로^^​​​​​​​​​​​​​#도시락             치킨너겟, 콩나물무침, 무말랭이피클, 김,샤인머스켓, 약과, 딸기우유        ​​​​​​#아침#아보카도닭가슴살샌드위치#방울토마토           운동#헬스장                    헬스장 등록 기간이 얼마 안남아서특히 열심히 가고 있다30분 유산소만 해도​다녀오면​몸이 한결 가벼워서 좋다​​​​​​#하교길                                                     애들 하교 버스 마중가는데흑곰인가요              털장갑, 털운동화 필수​날씨 변덕적응안대​​​​​​​#저녁식사#도토리건조묵골뱅이무침                                          우와이거 대박 맛났음​건조 묵... 좀 비쌌는데​다음 택배 받을때 좀 쟁여놔야게뜸​​​​​​#도시락#어린이도시락샌드위치#킨더하마초콜릿                                          맨날 냉털이래근데 샌드위치 속재료는 정말 있는거 없는거상할 것 같은 것도막 채워 넣는다그럼 그냥 맛나​​​메르로에서 우연히 발견한킨더하마초콜렛도​소문대로 맛있더군​​​​​​#패딩기간에 득템​​데헷맘에드로​​​​​#저녁메뉴#단호박에그스럿#패션후르츠#방울토마토#abc쥬스                               저녁 간단히​​단호박 에그슬럿은간단한듯 안간단...​맛은 쏘쏘​​​​​​​​​#velosan#독일#무쇠에그팬                             나​​​​​​​#도시락             장조림버터볶음밥, 녹두전, 샤인머스킷, 방울토마토, 오이,요거트견과류        ​​​​​​​#가정학습                                          조금 기침을 했지만​계속 등교를 시켰는데학교에선 가끔씩 심하게 기침 한다고속 누나랑 아빠 찾음)​​​​​​#소시지치즈또띠아롤#샤인머스킷#방울토마토#아이스아메리카노                                          치즈 잔뜩 소시지 계란 넣은 또띠아버터 넣은 팬에 굽굽하다롤롤​대박 느끠​​                    후식은 요요요요 맛매일 계속 한다​​​재밋나바​​​​#도시락#엄마표도시락             짜장밥, 발울토마토,무말랭이피클, 빼빼로, 요구르크, 샤인머스켓            김주먹밥, 치킨너겟, 오이피클, 패션푸르츠, 미니약과, 젤리        ​​​​​​​​#맥도날드#햄버거            ​​​​​기빨리고 정말 아무것도 하기 싫어서오전 내내 누워서 미드보다맥날 시켜 점심​​​​​​맥날은 나의 힘!​​​​저거 혼자 다 먹었다​​​​​​​​#드레곤우드게임                    하다하다둘이도 하고 혼자도 하고​​게임중독자들​​​​​​​#서프라이즈#airpod프라이즈로 사온 에어팟​​거마워🤍​​(근데 아마 자기 해드폰 사며 눈치보여 사온듯?!)​​​​​​​#모녀데이트#스타벅스                                                                           아들과 남편이 짐보리 갈때보통 집에 있는데​어제 하루종시간 지루하니공부할거, 독서할 것도 챙기고​완전 알찬 데이트였다‍❤️​딸 너무 좋앙​​​​​​#짐보리                               미술 수업인데얜 이수업이 쿠키먹는 수업인줄 안다​쿠키 먹는 수업만 되면​아이 라이크 쿠키를 그렇게 외치며 손을 든다고핑한다고 들렀는데이거저거 나에게 리젝 당하고​빈손으로 나옴​​​미얀​                               그래도 엄마 거셀은 좀 찌그껨​​​​​                    빈손이지만 쿨한 여자담에 꼭 필요한거 사자​​​​​​​​#운동#헬스장                         느낀건난 움직이고 활동해야오히려 힐링되는 사람​​오전 외출하고남편 대학원 수업 끝나자마자운동하러...​​유산소 운동 30분 겨우 했지만게운해​그럼 되찌 머​​​​​#저녁                               다이어트 절대 못하는 나인데​가끔 살이 빠지는 ​스트레스​​​​​​​🤮​​​​​​입맛 뚝​​간단히 저녁 먹기​​​​​​​그리고 썬데이투데이​​마사지 갔다 운동하고 밥먹고 또 침대에서 미드보고​정말 깨알같이 은근 많은걸 했는데아직 7시...​​​​​요몇일 정말 별거 아닌일(?)로 멘붕오고덕분에핑계로잘 쉬었다​​​우리끼리 행복하니 되쓰​​​​암오케이​​​​​​​​​​​​​​​​​​​​​​​​하지만...이러나저러나 빨리 ㅋㄹㄴ ㅆㄲ 사라져서한국가서 가족들 보고프다​(끝날듯 끝나지 않는 포슷힝)​​ 108. 잘먹고 잘살기


현재 0.8.2 버전에서도 libc++abi.dylib: terminating with uncaught exception of type kiwi::KiwiUnicodeException: unpaired surrogate
오류 발생합니다

**Comment by bab2min** [comment]
#25 이슈에서 다룹니다.
