### ISSUE TITLE
extract_words() 관련 문의

### ISSUE THREAD

**Issue by labbanym** [bab2min/kiwipiepy#22]
안녕하세요? 미등재어 추출에 관심이 있어 관련 정보를 찾다가 이 페이지까지 오게 되었습니다:)
kiwipiepy의 extract_words() 사용 예제를 보니 파일의 내용을 읽어 처리하는 방식인 것 같습니다.
DB에서 읽어 온 자료를 사용해 보고 싶은데 첫 번째 파라미터를 어떤 형식으로 넘겨 주면 가능할까요?

**Comment by bab2min** [comment]
답변이 늦어서 죄송합니다. 어떤 DB에서 읽어오는지에 따라 세부적인 코드는 조금씩 다르겠지만 개략적으로 아래처럼 쓰시면 될듯합니다.

```
kiwi = Kiwi()
class ReaderExam:
    def __init__(self, host, id, pw, port, db_name):
        self.conn= some_db_connection(host, id, pw, port, db_name)
    
    def read(self, idx):
        res = self.conn.query("SELECT sent FROM db LIMIT %s,1", idx)
        return res['sent']

reader = ReaderExam(**디비접속정보들)
kiwi.extractWords(reader.read, 10, 10, 0.25)
```
read(self, idx)메소드에서는 idx번째 문장을 반환하면 되므로, DB를 적절하게 조회하여 해당하는 문장을 반환해주시면 됩니다.

**Comment by terry-bae** [comment]
안녕하세요? 문장에서 형태소 전체를 토크나이저 하는게 아닌 특정 형태소만 해당되는 경우의 word만 토크나이저 할 수 있게하는 함수가 있을까요? 예를들면 어떤 문장에서 명사만 토크나이저하여 추출하고 싶은 경우가 있다면요

**Comment by bab2min** [comment]
안녕하세요 @terry-bae 
형태소 분석 결과에서 특정 형태소만 뽑아내고 싶으신 경우라면 extract_words() 함수를 사용하실 필요는 없구요, tokenize()함수 후 필터링만 해주시면 되겠습니다.
```python
from kiwipiepy import Kiwi
kiwi = Kiwi()
tokens = kiwi.tokenize("명사만 남기고 나머지는 없애주세요.")
nouns_only = [t for t in tokens if t.tag.startswith('NN')]
print(nouns_only)
# 출력 결과
# [Token(form='명사', tag='NNG', start=0, len=2), Token(form='나머지', tag='NNG', start=8, len=3)]
```
