### ISSUE TITLE
분석을 돌리면 단어가 바뀌는 현상?

### ISSUE THREAD

**Issue by SHwan93** [bab2min/kiwipiepy#27]
진짜 푸짐하고 뜨끈~하게 맛있는 감자탕 먹엇어용!
저는 감자탕하면 살코기는 별로 없고 뼈만 크다구 생각햇는데
완전 5산 오브 5산,,, 여긴시 살코기도 푸짐하고
식감도 부드러워서 너무 맛잇게 잘 먹엇다는 ㅜㅜ♥️
바람 쌩쌩불고 밖에 나가지도 못하는데
이렇게 든든하구 맛난 밀키트 하나만 잇어도
온 가족 저녁 걱정은 필요 없다구요🥺🥺♥️
라면사리랑 신선한 야채도 잘 포장되어 와서
양도 푸짐하니 든든한 느낌😌😌
감자도 포슬포슬하니 맛나고 따로 포장되어 좋앗어요🥰
국물도 맛잇어서 밥도 국물 사라질때까지 말아먹기 가능👍🏻
저에게 감자탕에 대한 편견을 깨준 감자탕패밀리!!
이젠 집에서 간단하게 끓이기만 해두 사먹는 것보다
맛잇게 먹을 수 잇는 시대라니,,, 넘나 좋은것

위 문장 분석시 "신선한 야채도 잘 포장되어 와서" 부분에서 와서가 왜 오어서로 변경되는건가요?

('포장', 'NNP', 205, 2), ('되', 'XSV', 207, 1), ('어', 'EC', 208, 1), ('오', 'VV', 211, 1), ('어서', 'EC', 210, 2), ('양도', 'NNG', 213, 2)

**Comment by SHwan93** [comment]
버전은 가장 최신입니다

**Comment by bab2min** [comment]
안녕하세요, @SHwan93 님
어미에 들어가는 아/어는 앞단어의 모음의 양성/음성 여부에 따라 형태만 달라집니다. kiwi에서는 효율적인 처리를 위해서 이렇게 형태만 다른 두 어미를 하나로 통합하여 처리하고 있습니다. Kiwi 생성시에 기본값으로 들어가는 Option 중 `Option.INTEGRATE_ALLOMORPH` 가 이렇게 서로 다른 어미를 통합하도록 하는 옵션입니다.

    Kiwi(num_workers=0, model_path='./', options=Option.LOAD_DEFAULT_DICTIONARY | Option.INTEGRATE_ALLOMORPH)

이를 끄시고 싶다면 Kiwi 생성시 `Option.INTEGRATE_ALLOMORPH`를 빼고 `Option.LOAD_DEFAULT_DICTIONARY`만 넣으시면 됩니다.

**Comment by SHwan93** [comment]
넵 답변 감사합니다!
