### ISSUE TITLE
나무위키를 분석하는데 320만~330만라인 쯤에서 항상 에러가 발생합니다.(코퍼스문제X)

### ISSUE THREAD

**Issue by DrinkingMilktea** [bab2min/kiwipiepy#33]
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
라는 에러가 발생하는데

재현을 위해서는
https://mu-star.net/wikidb
위 링크에서 2020/03 나무위키 덤프 파일을 다운받으시고
아래 코드를 실행하시면 됩니다.

코드는 매우 간단합니다.

`from namuwiki.extractor import extract_text

def work(document):
    return {
        'title': "#"+document['title'],
        'content': extract_text(document['text'])
    }

with open('namuwiki200302.json', 'r', encoding='utf-8') as input_file:
    namu_wiki = json.load(input_file)

with Pool() as pool:
    documents = pool.map(work, namu_wiki)

with open("namuextrac.txt", 'w', encoding='utf-8') as outf:
    for page in documents:
        outf.write(page['title']+"\n")
        outf.write(page['content']+"\n")
from kiwipiepy import Kiwi
kiwitags = ["NNG", "NNP", "XR", "VA", "VX", "SL"]

kiwi = Kiwi()
kiwi.load_user_dictionary('dicword.txt')
kiwi.prepare()

with open("namuextrac.txt", encoding='utf-8') as inf:
    with open("kiwi-namu.txt", 'w', encoding='utf-8') as outf:
        for i, result in enumerate(kiwi.analyze(inf.readlines())):
            if i % 100000 == 0:
                print(f'Analyzed {i}th row')
            outf.write(' '.join(map(lambda x: x[0] if x[1] in kiwitags else "", result[0][0])) + "\n")`

이렇게 매우 짧은 구성입니다.

실행환경은 3900X, 128GB입니다.
이외의 SSD와 GPU는 실행요소가 아니라서 기재하지 않았습니다.

항상 320만라인에서 330만라인쯤에서 에러가 발생합니다.
코퍼스의 문제인가 싶어 해당 라인을 찾아가 앞뒤로 10라인씩 지워봤지만
380만라인에서 에러가 발생하는 것으로 보아 에러의 발생을 늦출 뿐입니다.

혹시나 20개로 나눠서 동작시키면 가능할까 해보았지만
같은 에러가 뜨며 동작하지 않았고
20개의 파일을 수작업으로 하나씩 돌리고 파이썬이 완전히 종료된 후 다시 실행해보아도
매번 비슷한 320만 ~ 330만 라인쯤에서 에러가 발생합니다.
에러가 나는 정확한 위치는 계속 수십~수백라인사이에서 바뀌지만
문제가 되는 라인을 지우더라도 계속해서 에러는 다른 곳에서 발생합니다.

해당 에러메세지를 인터넷에 찾아보니 스레드가 서로 공유하는 메모리에서 변수를 바꾸는 것과 관련된 이슈로 보입니다.
디버깅 부탁드립니다.

**Comment by bab2min** [comment]
안녕하세요 @DrinkingMilktea 
버그 제보해주셔서 감사합니다. 공유주신 데이터 이용해서 디버깅해보겠습니다.

**Comment by DrinkingMilktea** [comment]
내용 업데이트 하겠습니다
특정 코퍼스에서 문제일 수도 있겠다는 의견입니다.
20가지로 나눠서 동작시켜봤는데
특정 코퍼스 집단에서만 문제가 발생합니다

확인하시는데 도움이 되기를 바랍니다.

**Comment by bab2min** [comment]
@DrinkingMilktea 
혹시 dicword.txt 파일을 공유해주실수 있으신가요? 일단 default dictionary 가지고 테스트를 해봤는데 에러가 재현되지 않아서요. 아마 user dictionary에 들어가는 엔트리 때문에 문제가 발생하는 것으로 보입니다. 해당 파일 공유주시면 추가적으로 디버깅해볼게요.

**Comment by DrinkingMilktea** [comment]
https://thxeksel.synology.me:5001/sharing/dCw63DdBh
dicword와 문제를 일으켰던 2번과 5번 분리파일과 제가 사용했던 wiki_extract.txt파일 모두 공유하겠습니다!

**Comment by bab2min** [comment]
@DrinkingMilktea 혹시 사용한 kiwipiepy 버전을 확인해주실 수 있나요? 일단 0.9.2에서 테스트해본 결과 해당 에러가 재현되지 않아서요. 혹시 0.9.0~0.9.1버전이시라면 메모리 관리 쪽이 불안정한 버그가 있는지라 그것 때문에 문제가 발생했을 수도 있어보입니다.

**Comment by DrinkingMilktea** [comment]
![Screenshot from 2021-02-14 13-59-38](https://user-images.githubusercontent.com/38062461/107869040-36b33f80-6ecd-11eb-946c-16f41f6410c6.png)
![Screenshot from 2021-02-14 14-00-30](https://user-images.githubusercontent.com/38062461/107869042-40d53e00-6ecd-11eb-9cf4-56d12b3ff665.png)

0.9.2버전으로 업그레이드하고 실행해도 마찬가지 입니다 ㅠㅠ
파이썬은 아나콘다 3.8을 쓰고 있으며
혹시나 CPU특성의 문제일까 노트북으로 실행해봐도 똑같은 결과가 나옵니다
간단한 코드로 생각되어 스크린샷도 첨부해보았습니다
혹시 제가 코드를 잘못 짠걸까요?

**Comment by bab2min** [comment]
@DrinkingMilktea 작성하신 코드에 문제는 없어보입니다.
일단 공유주신 데이터, 코드 가지고 좀 더 조사해보도록 하겠습니다.

**Comment by bab2min** [comment]
@DrinkingMilktea, 입력 데이터와 멀티 스레딩 사이의 복합적인 문제로 발생하는게 아닐까 싶습니다.
일단 Kiwi생성시 `Kiwi(num_workers=1)`로 하셔서 단일 스레드에서만 동작하게 하신 다음 다시 테스트를 진행해 주실 수 있나요?
만약 `num_workers=1`일때는 에러가 발생하지 않는다면 num_workers를 차차 키워가시면서 에러가 발생하는 스레드 개수를 확인해볼 수 있을듯 합니다.

**Comment by DrinkingMilktea** [comment]
오! 말씀 듣고 바로 시도해봤습니다
num_workers=1로 해도 에러가 뜨네요

![num_workers1](https://user-images.githubusercontent.com/38062461/107881374-70189900-6f27-11eb-9489-437e21b545b0.png)

**Comment by bab2min** [comment]
@DrinkingMilktea, 음 멀티스레딩으로 인한 문제는 아닌가보네요.
혹시 그럼 다음 코드로도 테스트해주실 수 있나요?

```
from kiwipiepy import Kiwi

kiwi = Kiwi(num_workers=1)
kiwi.load_user_dictionary('./dicword.txt')
kiwi.prepare()

with open('./namupart2.txt', 'r', encoding='utf-8') as inf:
    for i, x in enumerate(inf):
        result = kiwi.analyze(x)
        if i % 10000 == 0:
            print(f"analyze {i}st line")
    print(result)
```

**Comment by DrinkingMilktea** [comment]
동일한 에러가 납니다
![kiwitest](https://user-images.githubusercontent.com/38062461/107882311-e28b7800-6f2b-11eb-9f1a-406df8e966fd.png)

**Comment by bab2min** [comment]
@DrinkingMilktea 번거로울텐데 테스트해주시는 점 감사드립니다.
현재 의심 가는 부분은 0.9.0 버전에서 추가된 mimalloc 관련 기능입니다. 이를 확인해보기 위해서는 현재 설치된 kiwipiepy를 제거하시고 0.8.2버전을 설치해보시거나, 아니면 아래 올려드리는 wheel 파일로 kiwipiepy를 새로 설치해보시면 되겠습니다.

[kiwipiepy-0.9.2-cp38-cp38-manylinux2010_x86_64.zip](https://github.com/bab2min/kiwipiepy/files/5980755/kiwipiepy-0.9.2-cp38-cp38-manylinux2010_x86_64.zip)

위 zip파일 압축을 푸시면, `kiwipiepy-0.9.2-cp38-cp38-manylinux2010_x86_64.whl` 파일이 나오는데, kiwipiepy가 제거된 상태에서
```console
$ pip install kiwipiepy-0.9.2-cp38-cp38-manylinux2010_x86_64.whl
```
와 같은 식으로 사용하여 설치할 수 있습니다.

0.8.2버전과 위 버전으로 설치하신 뒤 동일한 문제가 발생하는지 확인해주시면 정말 감사하겠습니다.

**Comment by DrinkingMilktea** [comment]
@bab2min 안녕하세요 결과 알려드리겠습니다
![스크린샷, 2021-02-16 23-05-35](https://user-images.githubusercontent.com/38062461/108073536-82bbdb00-70ab-11eb-9bd5-1f6d7e0ecbb9.png)
0.8.2버전으로 설치하여 진행한 결과는 위와 같이 정상적으로 끝나는 것을 확인할 수 있었습니다.

그런데 기존 설치본을 삭제하고 첨부해주신 파일을 이용해서 재설치해본 결과는 위의 멘션과 마찬가지로 540000line까지 출력이 되고 똑같은 에러가 뜹니다.

확인 부탁드립니다.

**Comment by bab2min** [comment]
@DrinkingMilktea 매번 결과 공유해주셔서 감사합니다.
덕분에 mimalloc이 아니라 0.9.x버전 대에서 추가된 내부 기능에 의한 SEGFAULT인 것으로 원인이 좁혀졌네요. 
이쪽으로 해서 분석하도록 하겠습니다. 원인 파악되면 공유드리겠습니다. 그전까지는 0.8.x대를 사용하시는걸 권장드립니다.
다시 한 번 감사합니다.

**Comment by bab2min** [comment]
@DrinkingMilktea 조금 오래걸렸지만 오류의 원인이 파악되었습니다.

https://github.com/bab2min/kiwipiepy/issues/36#issuecomment-855269281

조만간 해당 오류를 수정한 버전을 배포하도록 하겠습니다. 다시 한 번 감사드립니다.

**Comment by DrinkingMilktea** [comment]
앗 축하드립니다
오늘 안그래도 버전 업그레이드가 되었나 확인하고 soynlp를 두리번 거리고 있었는데 ㅋㅋㅋㅋ
Kiwipiepy도 다시 후보군에 넣겠습니다!!

2021년 6월 6일 (일) 오전 2:21, bab2min ***@***.***>님이 작성:
