### ISSUE TITLE
[Question] 복합명사 등록은 할수 없는것인가요?

### ISSUE THREAD

**Issue by SHwan93** [bab2min/kiwipiepy#34]
할 수 있다면 어떤식으로 등록가능한지 알고 싶습니다

**Comment by bab2min** [comment]
@SHwan93 
현재 분석기가 공백으로 분리되지 않은 문자열에 대해서만 탐색을 수행하기에, 시스템 상 공백을 포함하는 경우라면 사용자사전에 등록할 수 없습니다. 
공백 없이 붙여서 적는다면 NNG나 NNP 등의 태그로 사용자 사전에 등록할 수 있습니다. 복합명사만을 위한 태그가 필요하신 거라면 다음 기능 업데이트 때 사용자 전용 태그를 추가해볼 수 있겠습니다.

**Comment by SHwan93** [comment]
기능 업데이트가 된다면 그때 다시 검토해보겠습니다 피드백 감사합니다^^
