### ISSUE TITLE
사용자 사전 추가시 100kb가 넘는 데이터에 관하여 형태소분석 수행불가

### ISSUE THREAD

**Issue by opopttt** [bab2min/kiwipiepy#36]
안녕하세요, 성능 좋은 형태소분석기 개발에 감사합니다.

현재 저는 ubuntu 21.04, python 3.9.4 환경에서 개발 중이며,
시스템은 Ryzen 3950x, RAM 32G*3, (samsung 980pro 1TB) 세팅으로 사용 중입니다.
개인적으로 구성한 아래 사용자 사전을 로딩하여 형태소 분석기 실행시 커널이 죽어버립니다(주피터 노트북).
py파일로 컴파일하여 터미널에서 실행시킬 경우 다음과 같은 오류를 호출합니다.
: 세그멘테이션 오류 (코어 덤프됨)

메모리 문제여서 시스템 사용량도 체크를 하였으나 해당 부분엔 로드가 없고
100kb이하의 텍스트 파일을 분석하는 별도의 py파일을 구성하고 터미널에서 반복 실행해야 오류가 나지 않는 것을 확인했습니다.(100kb가 넘는 데이터에 분석시 메모리 에러 발생)

사용자 사전이나 텍스트에서 단어사전을 추출하여 구성하는 기능을 사용하지 않으면 이러한 버그가 생기지 않습니다.

아래는 분석에 사용한 소스코드입니다. 필요하시면 이메일로 분석데이터도 보내드리겠습니다.

감사합니다.

```
from kiwipiepy import Kiwi
kiwi = Kiwi()
#no matter of num_workers or options

kiwi.load_user_dictionary('userDic.txt')
kiwi.prepare()

with open('corpus.txt', 'r') as file:
    corpus = file.readlines()

tokenList = {'NNG': '일반 명사', 'NNP': '고유 명사', 'VV': '동사', 'VA': '형용사'}
corpus2 = []
with open('/home/tony/reviews_tokenized.csv','a') as file:
    for item in kiwi.analyze(corpus):
        for token in item[0][0]:
            if token[1] in tokenList:
                file.write(token[0]+',')
        file.write('\n')
```

**Comment by bab2min** [comment]
안녕하세요 @opopttt 님, 상세한 오류 정보 공유해주셔서 고맙습니다.
테스트에 사용한 userDict.txt과 corpus.txt 파일을 메일로 공유해주신다면 원인 파악에 도움이 많이 될듯하네요.
공유해주신 파일은 테스트 이외의 용도로는 쓰이지 않고, 테스트 후에는 완전히 삭제하도록 하겠습니다.
다시 한 번 오류 제보에 감사드립니다.

**Comment by opopttt** [comment]
이메일 보냈습니다 :)

**Comment by bab2min** [comment]
드디어 오류 원인이 파악 완료됐습니다.

mimalloc & ubuntu 사용시에만 발생되던 교묘한 에러였는데, 사실 코어 모듈의 두 라인에서 KForm 후보 데이터 cand[0]이 다음 데이터 cand[1]과 동일한지 비교하는 로직이 원인. cand가 KForm의 제일 마지막 요소를 가리키는 경우 cand[1]은 out of range가 되어서 진작 에러가 났어야 했지만 default allocator를 사용하는 경우에는 넉넉하게 할당된 메모리로 인해 이런 문제가 발생하지 않았고, mimalloc & ubuntu에서만 문제가 발생한 것이었습니다.

https://github.com/bab2min/Kiwi/blob/971c646b66f63c79a7ba032ed010e37a826e85ea/src/core/KTrie.cpp#L226
https://github.com/bab2min/Kiwi/blob/971c646b66f63c79a7ba032ed010e37a826e85ea/src/core/KTrie.cpp#L263

이는 KForm 마지막 부분에 끝 부분임을 알리는 sentry를 추가함으로써 해결 가능합니다.

#33 이슈 역시 동일한 원인에 의한 것으로 확인됐습니다. 

조만간 해당 문제가 해결된 Kiwi & kiwipiepy를 배포하도록 하겠습니다. 오류 제보해주셔서 감사합니다 @opopttt

**Comment by opopttt** [comment]
와 정말 감사합니다.
미말록이 우분투와 호환할 때 발생하는 문제라니 상상도 가지 않습니다.
지속적인 사용으로 더 좋은 형태소 분석기 만들기 위해 노력하겠습니다.

혹시 키위에 형태소 분석기반 문장 분리 기능 넣을 생각있으면 말씀 주세요.
KSS 보다 키위 분석기를 활용한 종결어미 기반 문장분리기 성능이 더 좋은 것 같습니다.
뭐 어짜피 둘다 룰 기반 분리기라 빠른 건 매한가지지만요.
