### ISSUE TITLE
options=Option.INTEGRATE_ALLOMORPH을 사용하면 Segmentation fault 등 여러가지 에러가 뜹니다.

### ISSUE THREAD

**Issue by DrinkingMilktea** [bab2min/kiwipiepy#38]
![kiwi_error](https://user-images.githubusercontent.com/38062461/126057623-00174be1-3beb-48d1-8134-7bdf59ad05ff.png)
위 그림과 같이 매우 간단한 코드입니다.
kiwi를 옵션과 함께 불러오고
해당 문장을 analyze를 하면 segmentation fault가 뜹니다

옵션없이 kiwi = Kiwi()로 했을 때는 잘 됐습니다

혹시나싶어 반복적으로 시도해보았지만 같은 오류가 재현됩니다.

제 환경은 우분투 18.04.5 LTS
CPU : i7-8550U
Ram : 16GB
입니다.

**Comment by DrinkingMilktea** [comment]
core dump 파일은 너무 커서 여기 올라오지 않아 따로 아래 링크로 드리겠습니다
https://thxeksel.synology.me:5001/sharing/oWTo0QkOr

**Comment by bab2min** [comment]
@DrinkingMilktea 오류 제보 감사합니다. 
공유해주신 코드와 core dump로 원인 파악해보겠습니다~

**Comment by DrinkingMilktea** [comment]
다른 작업환경에서 다른 작업들도 해보는데 Kiwi의 options=Option.INTEGRATE_ALLOMORPH가 문제되는 것 같습니다.
해당 옵션을 빼면 정상동작합니다.

**Comment by bab2min** [comment]
안녕하세요 @DrinkingMilktea
오래 기다리셨죠..?
내부 언어 모델 엔진 쪽의 결함으로 판단되어 해당 부분을 새로 구현했습니다. test.pypi.org에서 테스트 버전을 미리 받아서 확인해보실 수 있습니다.

```console
pip install --index-url https://test.pypi.org/simple/ kiwipiepy==0.10.0
```
