### ISSUE TITLE
"그렇다" 와 "그러하다" 를 다르게 인식하는 문제가 있습니다.

### ISSUE THREAD

**Issue by tmvkrpxl0** [bab2min/kiwipiepy#44]
입력: "그건 그렇다.", "그건 그러하다."
[('그거', 'NP', 0, 2), ('ᆫ', 'JX', 2, 0), ('그렇', 'VA', 3, 2), ('다', 'EF', 5, 1), ('.', 'SF', 6, 1)]
[('그거', 'NP', 0, 2), ('ᆫ', 'JX', 2, 0), ('그러', 'XR', 3, 2), ('하', 'XSA', 5, 1), ('다', 'EF', 6, 1), ('.', 'SF', 7, 1)]
"그렇다" 와 "그러하다" 는 동일한 품사이며 동일한 의미입니다. 그러나 분석 결과는 위처럼 다르게 나옵니다.

**Comment by bab2min** [comment]
안녕하세요 @tmvkrpxl0 님, Kiwi에 관심을 가져주셔서 고맙습니다~!

해당 문제는 모델을 학습할때 사용한 세종계획 말뭉치에서 기인하는 문제인데요,
그 말뭉치를 구축시에 `그렇다`는 `그렇/VA + 다/EF`, `그러하다`는 `그러/XR + 하/XSA + 다/EF`와 같이 다르게 분석하였기 때문에 이 데이터를 학습한 모델도 마찬가지 결과를 내는 것으로 보입니다.
사실 이외에도 동일한 의미, 동일한 품사인데 표현이 약간 다르다고 다르게 분석한 경우가 꽤 많습니다. 아마 원 입력 텍스트를 최대한 따르는게 말뭉치 구축 원칙이 아니었나 싶네요.

현재로썬 학습 데이터 및 모델 자체를 교체하지 않는 이상 개선이 어렵구요, 후처리로 위와 같은 케이스들을 통합시켜주는 기능을 추가하는건 가능해보입니다.
