### ISSUE TITLE
고유명사 사용자 사전 등록

### ISSUE THREAD

**Issue by wo7897** [bab2min/kiwipiepy#58]
README에 나와있는 사용자 사전 추가 내용 중에 

\# 스타크래프트 관련 명사 목록
스타크래프트  NNP 3.0
저글링 NNP
울트라리스크 NNP  3.0

1) 위 사용자 사전 파일 내용 중 '울트라리스크'와 같이 두 개 이상의 형태소로 잘게 쪼개지는 고유명사를 하나의 형태소 NNP로 분석이 가능한가요? 
위 사용자 사전 파일 내용을 아래와 같이 호출시 결과에 사용자 사전 적용 이전과 동일하게 나오는 것 같습니다.

```
def main():
    kiwi = Kiwi()
    print(kiwi.load_user_dictionary(dict_path='userdic.txt'))
    kiwi.prepare()
    result = kiwi.analyze('울트라리스크가 뭐야?')
    print(result)
```
`[([Token(form='울트라', tag='NNG', start=0, len=3), Token(form='리스크', tag='NNG', start=3, len=3), Token(form='가', tag='JKS', start=6, len=1), Token(form='뭐', tag='NP', start=8, len=1), Token(form='이', tag='VCP', start=9, len=1), Token(form='야', tag='EF', start=9, len=1), Token(form='?', tag='SF', start=10, len=1)], -38.33686447143555)]`

2. 사용자 사전을 적용해보는 도중에 사용자 사전 단어 순서에 따라 사전 내용 적용 유무가 달라지는 것을 확인했는데 사용자 사전에서 단어 순서도 분석 내용에 영향이 있나요?
확인해본 케이스는 아래와 같습니다. 

```
\# userdict1
울트라리스크	NNP	3.0
파일즈	NNG	0.0
```

위 파일을 1번 코드 내용과 같이 동일하게 호출하여 분석 시 '울트라리스크'가 NNP로 분석이 되고 있습니다.
`([Token(form='울트라리스크', tag='NNP', start=0, len=6), Token(form='가', tag='JKS', start=6, len=1), Token(form='뭐', tag='NP', start=8, len=1), Token(form='이', tag='VCP', start=9, len=1), Token(form='야', tag='EF', start=9, len=1), Token(form='?', tag='SF', start=10, len=1)], -12.41728687286377)`

```
\# userdict2
파일즈	NNG	0.0
울트라리스크	NNP	3.0
```

위 파일을 1번 코드 내용과 같이 동일하게 호출하여 분석 시 '울트라' '리스크'로 쪼개져서 분석이 되고 있습니다.
`([Token(form='울트라', tag='NNG', start=0, len=3), Token(form='리스크', tag='NNG', start=3, len=3), Token(form='가', tag='JKS', start=6, len=1), Token(form='뭐', tag='NP', start=8, len=1), Token(form='이', tag='VCP', start=9, len=1), Token(form='야', tag='EF', start=9, len=1), Token(form='?', tag='SF', start=10, len=1)], -38.33686447143555)`

감사합니다.

**Comment by bab2min** [comment]
@wo7897 
해당 문제에 대한 패치는 조만간 배포될 0.10.2버전에 포함될 예정입니다.
