### ISSUE TITLE
사용 방법 문의

### ISSUE THREAD

**Issue by rumbarum** [bab2min/kiwipiepy#6]
안녕하세요 @bad2min님, 최신이 최고야! 라는 생각에 kiwi가지고 형태소 분석을 해보고 있습니다. 
사용하는 중 문의사항이 있어 문의 드립니다. 

1. extractWords method 를 분석 했을때 나오는 점수들의 의미가 궁금합니다.
샘플 결과 ('브랜드', 4.506464004516602, 22, -2.085695505142212)
각각의 의미와 숫자들이 어떤 방식으로 매겨지는지 알고 싶습니다.

2. extract_add_words method를 통해 추가되는 사용자 사전은 해당 클래스에만 적용이 되고 파이썬 인터프리터 종료시 종료되는 일시적인 사전으로 봐야하는지 궁금합니다. 그리고 저장시 단어명 tab NNP tab 스코어 로 저장이 되는지, 아니면 단어명 Tab NNP 로 저장이 되는지 문의합니다. 

3. 사용자 사전의 단어 점수의 범위는 어떻게 될까요? soynlp는 0~1 이었는데 예시에 3이 있어서 얼마가 최대인지 궁금합니다.

감사합니다.

**Comment by bab2min** [comment]
부족한 라이브러리에 많은 관심을 가져주셔서 감사합니다!
도큐멘테이션이 부족한 부분이 있었네요. 

1. 반환값은 (형태, 최종스코어, 출현빈도, 품사스코어)입니다.
최종스코어는 cohesion 스코어와 branching entropy 스코어를 곱한값으로 계산되며 이 값이 클수록 해당 문자열이 뭉쳐서 등장하면서 문자열 앞뒤로 다양한 단어가 붙는다고 해석할 수 있습니다.
품사스코어는 이 단어가 명사일 가능성을 나타냅니다. 클수록 명사일 가능성이 높습니다.

2. 해당 클래스에만 추가되며, 종료시 사라지는 일시적인 사전입니다. 만약 여기서 추출된 단어 결과를 다른 분석에도 응용하고 싶으시다면, extractWords로 단어를 뽑아내어 사용자사전 형태로 저장하고 Kiwi 실행시 load_user_dictionary를 써야합니다.
extract_add_words를 사용시 추출된 단어 단어명 tab NNP 등의 파일 형태로 저장되지는 않고, 내부적인 사전 메모리에만 적재됩니다.

3. 단어 점수 범위는 제한이 없고 0 이상의 수면 다 가능합니다. 이 수치는 최종 분석결과를 정렬하는데에 사용됩니다. 예를 들어, '둘러싸이다'라는 문자열을 분석하기 전에 '러싸이'라는 고유명사를 등록하는 경우를 생각해보시면

``
kiwi.add_user_word('러싸이', 'NNP', 0)
kiwi.prepare()
kiwi.analyze('둘러싸이다', top_n=3)
# ([('둘러싸이', 'VV', 0, 4), ('다', 'EC', 4, 1)], -29.477783203125), 
# ([('둘러싸', 'VV', 0, 3), ('이', 'VCP', 3, 1), ('다', 'EC', 4, 1)], -31.870361328125), 
# ([('둘', 'NR', 0, 1), ('러싸이', 'NNP', 1, 3), ('다', 'EC', 4, 1)], -32.76953125)
``

위와 같은 결과가 나타납니다. 각 점수는 해당 단어가 등장할 확률과 해당 단어가 특정 단어열 뒤에서 등장할 확률을 조합하여 계산되는데, '둘' 바로 다음에 '러싸이'라는 고유명사가 나오고 어미 '다'가 붙을 확률이 낮기 때문에 둘러싸이/VV + 다/EC 가 1순위로 출력됩니다.
그런데 여기서 '러싸이'의 점수를 더 높게 설정하면 결과가 달라집니다.

``
kiwi.add_user_word('러싸이', 'NNP', 5)
kiwi.prepare()
kiwi.analyze('둘러싸이다', top_n=3)
# ([('둘', 'NR', 0, 1), ('러싸이', 'NNP', 1, 3), ('다', 'EC', 4, 1)], -27.76953125), 
# ([('둘러싸이', 'VV', 0, 4), ('다', 'EC', 4, 1)], -29.477783203125), 
# ([('둘', 'NR', 0, 1), ('러싸이', 'NNP', 1, 3), ('다', 'MAG', 4, 1)], -30.814697265625)
``
'러싸이'를 포함하는 분석결과의 점수가 5점씩 상승하면서 둘/NR + 러싸이/NNP + 다/EC 의 결과가 1순위로 바뀌게 됩니다.
적절한 수치를 잘 모르겠는 경우는 기본값인 0을 사용하시면 되며, 단어를 등록했는데도 분석결과에 나오지 않으면 수치를 키우시면 됩니다. 해당 단어가 분석결과에 꼭 나오게 하고 싶으시다면 10 이상의 큰 값을 입력하시면 됩니다.

**Comment by rumbarum** [comment]
상세한 설명에 감사드립니다!
