### ISSUE TITLE
문의사항

### ISSUE THREAD

**Issue by smbslt3** [bab2min/kiwipiepy#75]
안녕하세요 사용 중에 문의사항이 생겨 이슈 남깁니다

1. 사용자 사전 추가
` Kiwi.add_user_word(word, pos, score, orig_word=None)`
위 코드로 사용사 단어를 추가하려 하면, pos argument가 없다고 나오네요
따로 키워드를 명시하지 않고 넣으면 돌아는 갑니다
내부적으로 함수의 키워드가 바뀌었는데 설명에 반영이 아직 안된건가요?

2. 형태소 분석 후 종성
`가족적인 분위기`를 분석하면  ['가족', '적', '이', 'ᆫ', '분위기']  로 결과가 나오는데,
이때 종성인 ㄴ이 일반적인 키보드로 입력하는 ㄱㄴㄷㄹ...의 ㄴ이 아닌걸로 나오네요
종성이 분리되는 것 까진 괜찮은데, 이게 regex의 ㄱ-ㅎ 범위에 포함되지 않아 문제입니다.
혹시 이걸 일반적인 자음으로 바꿀 수 있는 옵션을 추가해주실 수 있나요?

그럼 좋은 형태소 분석기 만들어주셔서 감사합니다.

**Comment by bab2min** [comment]
@smbslt3 안녕하세요~
1. 예리한 제보 감사합니다. README.md의 document에 인수 이름이 잘못 들어가 있었네요.
https://github.com/bab2min/kiwipiepy/blob/f70d22e7e360b4a9ae4e1125fdafc7739755f19f/kiwipiepy/_wrap.py#L78-L83
코드에서 확인하실 수 있듯, 두번째 인자가 `pos`가 아니라 `tag`로 들어가 있어야 하는데 문서 작성 과정에서 잘못 들어갔나보네요. 수정하도록 할게요.

2. Kiwi에서는 일반적인 호환용 자모 `ㄱㄴㄷㄹ...ㅎ` 및 `ㅏㅑㅓㅕ...ㅣ`는 기호로써의 한글 자모를 나타내기 위해, 첫가끝 코드의 종성(U+11A8 ~ 11C2)  `ᆫᆷ` 등은 어미나 조사를 나타내기 위해 구분되어 쓰이고 있습니다. 따라서 이를 통합하기 위한 옵션은 제공되지 않을 예정이며, regex에서 첫가끝 코드의 종성을 탐색하기 위해서는 `'[ㄱ-ㅎ]'` 대신 `'[ᆨ-ᇂ]'`을 사용하시거나 코드포인트를 직접 명시하여 `'[\u11A8-\u11C2]'`를 사용하시면 될듯 합니다.

**Comment by smbslt3** [comment]
답변 감사합니다 첫가끝 코드는 처음 알았네요 첫가끝 코드가 쓰이는 것은 형태소 분석 시 종성에서만 나타나는건가요? 이를 대체하는 코드를 짜려는데 첫 가 끝 각각을 해야할지 끝 코드만 신경써도 될지 범위를 알 수가 없네요

**Comment by bab2min** [comment]
@smbslt3  네, Kiwi 분석 결과에서는 첫가끝 코드의 종성만 쓰입니다.

**Comment by smbslt3** [comment]
@bab2min  알려주신 것을 바탕으로 [한글 낱자 목록](https://ko.wikipedia.org/wiki/%ED%95%9C%EA%B8%80_%EB%82%B1%EC%9E%90_%EB%AA%A9%EB%A1%9D) 문서를 참고해서 변환 코드를 작성했더니 잘 해결되었습니다.  좋은 라이브러리 개발해주셔서 감사합니다 :)
