### ISSUE TITLE
소수점 과 kiwipiepy_model 문의

### ISSUE THREAD

**Issue by nowtoday** [bab2min/kiwipiepy#79]
아래와 같이 소수점이 있는 문장은 두개의 문장으로 분리되길래... 혹시 별도 설정이 필요할지 문의드립니다.
사용자 단어로 0.1 혹은 0.1%를 추가해도 단어로 인식이 안돼서...

EBS 부모특강 - 0.1%의 비밀

EBS/SL + 부모/NNG + 특강/NNG + -/SO + 0/SN + ./SF
1/SN + %/SW + 의/JKG + 비밀/NNG

위와 같은 간단한 문장 테스트는 Kiwi_Gui 에서 먼저 테스트를 하는 경우가 있는데
우연잖게 이번에 배포해주신 Kiwi_Gui의 model 과 kiwipiepy_model 을 보게 되었는데 combiningRule.txt 이 다른 듯해서요...
kiwipiepy 업데이트시 kiwipiepy_model 가 같이 업데이트 되는 것 같지는 않기도 해서 따로 업데이트 해봤는데도 다르네요...
(나머지 파일들은 바이너리 비교해 보진 않았지만  날짜만 다른 것 같기는 한데...)

**Comment by bab2min** [comment]
안녕하세요 @nowtoday ,
`kiwipiepy_model`은 `Kiwi`의 메이저나 마이너 버전이 변경될때마다 업데이트하고 있습니다. 0.11.x 버전 내에서는 모델 파일들이 서로 호환되게 하기 위함입니다. Kiwi 0.11.0에서 0.11.1로 올라가면서 combiningRule.txt의 사소한 변경이 있었는데요 ( https://github.com/bab2min/Kiwi/commit/a5d190972b595733271c0e2e4fcae37fc5d3e685 ), 이 변경사항은 현재 kiwipiepy_model에 적용되지 않았으나, `더버라`, `추버라` 같은 ㅂ불규칙 관련 방언 외에는 분석 결과에 영향을 미치지는 않습니다. 이 변경사항들은 추후 kiwipiepy_model 0.12.0가 배포될때 반영될 예정인데, 그 이전에 사용하고 싶으시다면 최신 버전인 Kiwi 0.11.2의 모델 파일(https://github.com/bab2min/Kiwi/releases/tag/v0.11.2) 을 다운받아서 사용하시면 되겠습니다.

**Comment by bab2min** [comment]
@nowtoday 0.12.0 버전에서 소수점 분할 버그는 해결되었습니다~
