### ISSUE TITLE
종결어미와 부사격조사가 함께 쓰인 부분을 문장으로 분리해버리는 이슈

### ISSUE THREAD

**Issue by mel-f-dev** [bab2min/kiwipiepy#80]
아래의 문장이 포함된 문단을 split_into_sents을 사용해 분절했을 때 문장이 아래와 같이 두 문장으로 분리됩니다.   

1) Amazon Smbhav Venture Fund라는 이름의 해당 펀드를 통해 Amazon은 SMB들이 온라인을 통해 상품을 판매하고, 사업 운영을 디지털화 및 자동화함으로써 사업 범위를 해외로 확장할 수 있도록 돕는 스타트업들에 투자할 계획으로 총 몇 년 동안 펀드를 운영하게 될 지
2) 에 대해서는 공개하지 않았습니다.

품사를 확인해보니 '-ㄹ 지'를 종결 어미로 인식해서 그 뒤에 나오는 부사격 조사인 '에'와 함께 쓰였을 경우를 구분하지 못하는 것 같습니다.

Token(form='하', tag='XSV', start=152, len=1)
Token(form='게', tag='EC', start=153, len=1)
Token(form='되', tag='VV', start=155, len=1)
Token(form='ᆯ', tag='ETM', start=155, len=1)
Token(form='지', tag='EF', start=157, len=1)
Token(form='에', tag='JKB', start=158, len=1)

이 경우 어떤 방향으로 해결해 나갈 수 있을까요?

**Comment by bab2min** [comment]
반갑습니다~ @mel-f-dev 님,
그런 문제 사례들이 있을 수 있다는 걸 몰랐네요~ 좋은 제보 감사합니다.
찾아보니 문장 내에 다른 문장이 안겨있는 경우(복문), 위와 같은 문제가 발생할 수 있네요.
```python
>>> kiwi.split_into_sents('지도부가 어떻게 구성되느냐에 따라', return_tokens=False)   
[Sentence(text='지도부가 어떻게 구성되느냐', start=0, end=14, tokens=None), 
 Sentence(text='에 따라', start=14, end=18, tokens=None)]

>>> kiwi.split_into_sents('접어들 수 있는지를', return_tokens=False)
[Sentence(text='접어들 수 있는지', start=0, end=9, tokens=None), 
 Sentence(text='를', start=9, end=10, tokens=None)]
```
학습에 사용하는 모두의 말뭉치 형태분석 말뭉치 데이터를 확인해보니, 위와 같은 사례들의 어미가 다 종결어미 `EF`로 태깅되어 있어서, `EF`만 이용해서 문장 경계를 구분하면 동일한 문제가 계속 반복될 걸로 보여요.
따라서 문장 경계 판단시에 `EF` 태그 뒤에 조사가 바로 붙는 경우는 경계가 아닌 걸로 판단하도록 수정해야 할듯하네요~

**Comment by bab2min** [comment]
Kiwi 구현 내 문장 분리 함수: https://github.com/bab2min/Kiwi/blob/899c1c48f4dcaa6e69942d7da815a052d33906a9/src/Kiwi.cpp#L120-L193
`EF` 다음에 `J?`가 뒤따르는 경우는 sentPos를 증가시키지 않도록 수정 필요.

**Comment by bab2min** [comment]
@mel-f-dev 분리로직이 c++ 코어단에 적용되어있어서 파이썬 쪽에서는 직접 수정하기는 어렵구요, 후처리에서 이전 문장의 마지막 형태소가 `ef`이고, 다음 문장의 첫 형태소가 `j?`인 경우 합쳐주는 식으로 교정할 수는 있겠네요.
이 이슈의 수정패치는 다음 0.12 버전에 반영될 예정이긴 한데, 급하시다면 dev버전을 빠르게 올려드릴 수 있어요.

**Comment by mel-f-dev** [comment]
급하지 않아서 제가 후처리 해서 사용하겠습니다! :) 감사합니다!
