### ISSUE TITLE
12.0 버전에서는 기본 stopwords.txt 가 없어진건가요?

### ISSUE THREAD

**Issue by nowtoday** [bab2min/kiwipiepy#83]
이전에는 stopwords.txt 기본값이 있었던 것 같은데 이번 버전에는 없는 듯 보이는군요...
소스상에는 test_corpus에 custom_stopwords.txt으로는 있던데
기존에 제가 만들어 둔 것에는 stopwords를 정의하는 루틴이 있는데 kiwipiepy/corpus/stopwords.txt 에 파일이 없다고 종료되길래요...

**Comment by bab2min** [comment]
@nowtoday 제보 감사합니다.
확인 결과 0.12.0 버전 패키징 과정에서 해당 파일이 누락되었네요. 다음 업데이트에서 바로 수정하도록 하겠습니다~
급하시다면 https://github.com/bab2min/kiwipiepy/blob/main/kiwipiepy/corpus/stopwords.txt 에 있는 파일을 받으셔서 사용하셔도 되겠습니다.
