### ISSUE TITLE
인용문이 여러개 포함된 문장을 인식하지 못하는 문제

### ISSUE THREAD

**Issue by mel-f-dev** [bab2min/kiwipiepy#84]
안녕하세요,
지난 번에 빠른 피드백으로 많은 도움 얻었습니다.
계속해서 같은 모듈 사용 중에 문제가 발생했는데요,
문장 안에 인용문이 여러개 포함되어 있을 경우에 문장을 하나로 파악하지 못하는 것 같습니다.

예를 들어 아래와 같은 문장의 경우 세 문장으로 구분을 해냅니다.

 '조현준 효성그룹 회장도 신년사를 통해 “속도와 효율성에 기반한 민첩한 조직으로 탈바꿈해야 한다며 “이를 위해 무엇보다 데이터베이스 경영이 뒷받침돼야 한다”고 말했다.'

 ['조현준 효성그룹 회장도 신년사를 통해 “속도와 효율성에 기반한 민첩한 조직으로 탈바꿈해야 한다”',
 '며 “이를 위해 무엇보다 데이터베이스 경영이 뒷받침돼야 한다”',
 '고 말했다.']

이 경우 어떤 것이 문제이고, 어떻게 해결 가능할까요?

**Comment by bab2min** [comment]
안녕하세요~ @mel-f-dev 좋은 제보 감사합니다.
현재 Kiwi의 문장 분리 기능은 직접 인용문 등의 겹문장을 지원하지 못하는 한계가 있습니다. 겹문장의 경우 문장 분리시 고려해야할 점들이 많아서 간단한 규칙으로는 처리하기 어려운데요, 일단 추후 개발 계획에 넣어놓고 틈틈이 구현해보도록 하겠습니다.

다만 따옴표가 명확하게 삽입된 직접 인용문에 대해서는 규칙에 기반해 어느 정도 보정이 가능해보입니다.
1. 분리된 문장이 닫는 따옴표로 끝났지만
2. 여는 따옴표가 문장 제일 앞에 있지 않고 중간에 있는 경우는 다음 문장 조각과 결합
위와 같은 규칙으로 위의 오분할을 해결할 수 있을 걸로 보이네요~ 일단은 Python단에서 위와 같은 방식으로 후처리하여 사용하시는 걸 권장드립니다.

**Comment by bab2min** [comment]
@mel-f-dev 
0.14.0 버전에서 하위 문장이 포함된 경우의 문장 분리를 개선했습니다. 이제 인용문 등으로 안에 포함된 문장은 문장 분리 경계로 처리되지 않으며, 문장 속 문장들은 별도로 추출되어 subs 필드에 저장됩니다.
```python
>>> kiwi.split_into_sents('조현준 효성그룹 회장도 신년사를 통해 “속도와 효율성에 기반한 민첩한 조직으로 탈바꿈해야 한다”며 “이를 위해 무엇보다 데이터베이스 경영이 뒷받침 
돼야 한다”고 말했다.')
[Sentence(text='조현준 효성그룹 회장도 신년사를 통해 “속도와 효율성에 기반한 민첩한 조직으로 탈바꿈해야 한다”며 “이를 위해 무엇보다 데이터베이스 경영이 뒷받침돼야 한다”고
 말했다.', start=0, end=93, tokens=None, subs=[
  Sentence(text='속도와 효율성에 기반한 민첩한 조직으로 탈바꿈해야 한다', start=22, end=52, tokens=None, subs=None), 
  Sentence(text='이를 위해 무엇보다 데이터베이스 경영이 뒷받침돼야 한다', start=56, end=86, tokens=None, subs=None)
])]
```

**Comment by mel-f-dev** [comment]
개선 감사합니다! :)
