### ISSUE TITLE
띄어쓰기 및 원형 복구 문제

### ISSUE THREAD

**Issue by eubinecto** [bab2min/kiwipiepy#86]
안녕하세요!  
전 현재 [형태소 분석기가 필요한 라이브러리](https://github.com/eubinecto/politely)를 개발중인 개발자입니다. 지금은 khaiii를 사용중인데요. khaiii가 다른건 다 좋은데 배포하는게 까다로워요. 그래서 배포가 훨씬 간편한 kiwipiepy로 이전하려고 하는데요.

다만 문제가 하나 있어요. 제 프로젝트는 입력으로 주어지는 문장 속 띄어쓰기와 형태소 분석 이전의 원형을 복구하는 기능을 필요로 하는데요. 그게 khaiii에서는 쉽지만 kiwipiepy에서는 그렇지 않은 것 같아요.

예를 들어볼게요. 우선 khaiii를 사용하면 다음과 같이 토큰화 후에도 손쉽게 띄어쓰기와 원형을 복구할 수 있어요:
```python
sent = "시끄럽게 코고는 소리에 놀라서 난 잠이 깼다."
api = KhaiiiApi()
    tokens = api.analyze(sent)
    print(" ".join([token.lex for token in tokens]))
```
```
시끄럽게 코고는 소리에 놀라서 난 잠이 깼다.
```

반면,  kiwipiepy를 사용해서 똑같은 기능을 구현하는 것이 쉽지도, 정확하지도 않아요. 우선 띄어쓰기 복구는 `token.start`와 `token.len`을 잘 활용해서 어찌저찌 가능은 하지만, 아래처럼 코드가 khaiii에 비해 너무 지저분해집니다. 그리고 띄어쓰기를 복구하더라도, khaiii처럼 입력된 원형을 접근하는 방법이 없어요. 그래서  아래처럼 `코고는`이 `코골는`으로, `놀라서`가 `놀라어서`로 훼손돼요.
```python
sent = "시끄럽게 코고는 소리에 놀라서 난 잠이 깼다."
kiwi = Kiwi()
    tokens = kiwi.tokenize(sent)
    starts = np.array([token.start for token in tokens] + [0])
    lens = np.array([token.len for token in tokens] + [0])
    sums = np.array(starts) + np.array(lens)
    spacings = (starts[1:] - sums[:-1]) > 0  # if it is greater than 1, than it should be spaced.
    texts = [token.form + " " if spacing else token.form for token, spacing in zip(tokens, spacings)]
    sent = "".join(texts)
    print(sent)
```
```
시끄럽게 코골는 소리에 놀라어서 난 잠이 깨었다.
```

이 문제만 khaiii처럼 해결만 된다면 바로 kiwipiepy로 이전이 가능할 것 같은데요.  혹시 이 부분 패치가 가능할까요?

좋은 라이브러리를 계속 업데이트 해주셔서 감사합니다 :)

**Comment by bab2min** [comment]
안녕하세요 @eubinecto ~ 멋진 라이브러리를 개발하고 계시네요. `politely`에 `kiwipiepy`가 도움이 될 수 있으면 정말 좋을것 같은데요~
아마 0.12.0버전부터 추가된 `Kiwi.join` 메서드가 도움이 될 수 있을 걸로 보입니다. `Kiwi.join`은 형태소들을 결합해서 텍스트를 복원하는 메소드입니다. 
```python
sent = "시끄럽게 코고는 소리에 놀라서 난 잠이 깼다."
kiwi = Kiwi()
tokens = kiwi.tokenize(sent)
restored_sent = kiwi.join(tokens)
print(restored_sent)
# 시끄럽게 코 고는 소리에 놀라서 나는 잠이 깼다.
```
단, join시 공백 정보가 없더라도 품사를 이용해 알아서 공백을 넣어주기 때문에, 복원된 텍스트가 원문과 반드시 일치하지 않을 수도 있습니다. [README의 분석 단락](https://github.com/bab2min/kiwipiepy#%EB%B6%84%EC%84%9D)의 join 메소드 부분에서 좀 더 구체적인 내용을 보실 수 있습니다.
