### ISSUE TITLE
reader와 receiver 파이썬 리스트 활용 가능 여부

### ISSUE THREAD

**Issue by ByungjunKim** [bab2min/kiwipiepy#9]
안녕하세요. 키위를 연구에 활용중인 대학원생입니다.
bab2min님 블로그도 자주 들어가서 보고있는데요. 이자리를 빌어 감사의 말씀 드리고 싶습니다.
얼마전에 석사논문도 읽었는데 좋은 연구 논문이었습니다. 저에게도 많은 영감을 주셔서 또한 감사합니다.

다름이 아니라 토크나이징에서 reader 와 receiver를 따로 분리해 속도를 높일 수 있는데요.
1) 이걸 파이썬 리스트 형태로 receiver 처리가 가능한건지 예컨대 파일 형태로 write 하는 것이 아니라 바로 파이썬 리스트에 저장하면 속도가 떨어지는지요?
2) 또한 reader, receiver를 따로 설정해 토크나이징 할 경우 블로그에서 쓰신 것처럼 사용자에 맞는 토크나이징이 가능한지 궁금합니다. 아래는 블로그에서 보여주신 코드 입니다.

def tokenize(sent):
    res, score = kiwi.analyze(sent)[0] # 첫번째 결과를 사용
    return [word + ('다' if tag.startswith('V') else '') # 동사에는 '다'를 붙여줌
            for word, tag, _, _ in res\
            if not tag.startswith('E') and not tag.startswith('J') and not tag.startswith('S') and word not in stopwords] # 조사, 어미, 특수기호 및 stopwords에 포함된 단어는 제거

**Comment by bab2min** [comment]
이렇게 방문해주시고 관심가져주셔서 감사합니다.

1. 아니요, 문제 없습니다. reader, receiver를 사용하면 여러 문장들을 동시에 입력받고 동시에 처리할수 있어서 빠르다는 것이지, 파일에 저장하는 건 전혀 관계 없습니다.
2. 가능합니다.

```
from kiwipiepy import Kiwi

class IOHandler:
    def __init__(self, input):
        self.input = open(input, encoding='utf-8')
        self.result = []

    def read(self, sent_id):
        if sent_id == 0:
            self.input.seek(0)
            self.iter = iter(self.input)
        try:
            return next(self.iter)
        except StopIteration:
            return None

    def write(self, sent_id, res):
        filtered = []
        for word, tag, _, _, in res[0][0]:
            if not tag.startswith('E') and not tag.startswith('J') and not tag.startswith('S'): 
                filtered.append(word + ('다' if tag.startswith('V') else ''))
        self.result.append(filtered)

    def __del__(self):
        self.input.close()

kiwi = Kiwi()
kiwi.load_user_dictionary('userDict.txt')
kiwi.prepare()
handle = IOHandler('test.txt')
kiwi.analyze(handle.read, handle.write)

handle.result 
# 여기에 조사, 어미, 특수기호 등이 제거되고, 동사에는 '다'가 덧붙은 결과가 저장됩니다.
# 이걸 가지고 하고싶으신걸 하시면 됩니다!

```

**Comment by ByungjunKim** [comment]
감사합니다. 이렇게 자세한 답변까지 해주시고. 새해 복 많이 받으시고, 논문 쓰면서 kiwi를 계속 인용하면서 작업하겠습니다. 좋은 라이브러리 만들어주신거 다시한번 감사합니다.
