### ISSUE TITLE
오타교정 기능과 join 기능을 동시에 활용시 발생하는 에러

### ISSUE THREAD

**Issue by opopttt** [bab2min/kiwipiepy#92]
안녕하세요, 잘쓰고 있습니다.

다음과 같은 코드 실행시 컴파일러가 튕기는 에러가 발생합니다.

```
from kiwipiepy import Kiwi
kiwi = Kiwi(typos='basic')
kiwi.join(kiwi.analyze('쁘'))
```

'쁘' 외에도 쁜, 쁨, 쯔, 쯥, 조아 등이 input으로 들어가면 같은 에러가 발생합니다.

또한 typos 기능 사용시 튜플형태의 문장을 입력하면 에러가 발생합니다.

```
from kiwipiepy import Kiwi
kiwi = Kiwi(typos='basic')
kiwi.join([('사랑','NNG')])
```

감사합니다.

**Comment by bab2min** [comment]
안녕하세요 @opopttt 
오류 제보에 감사드립니다. 먼저 첫번째 오류의 경우 잘못된 타입의 입력이 들어온 경우 예외를 발생시키는 쪽에 버그가 있어 파이썬 인터프리터가 종료되는 것으로 확인되었습니다. analyze 대신에 tokenize 메소드를 사용하시는게 맞습니다.
```python
kiwi = Kiwi(typos='basic')
kiwi.join(kiwi.tokenize('쁘'))
```
그러나 현재 구현에서 오타 교정 기능이 켜진 경우 `join`이 잘못 동작하는 오류가 있어서 어떤 경우에도 오타 교정 기능이 켜져있을때 `kiwi.join`을 사용하면 크래시가 발생하는 것으로 보입니다. 다음 패치에서 이 부분을 수정하도록 하겠습니다.
