### ISSUE TITLE
숫자를 포함한 고유명사를 인식 하지 못 하는 경우 (추가)

### ISSUE THREAD

**Issue by joinmateFirst** [bab2min/kiwipiepy#93]
안녕하세요!
아래에도 등록된 이슈와 같이 
'k9', 'k55' 등 영문+숫자, 한글+숫자로 이루어진 단어의 경우 사용자 사전에 추가를 해도 토크나이징이 제대로 되지 않는 현상이 있습니다. 

제가 사용하는 버젼은  kiwipiepy v0.13.1 이구요.

"k9 k55" 를 토크나이징 했을 때 결과는 아래와 같습니다. 

---------------------------------------------------------------------
kiwi.add_user_word("k9", "NNP")
kiwi.add_user_word("k55", "NNP")
kiwi.tokenize("K9 K55")
---------------------------------------------------------------------

[Token(form='K', tag='SL', start=0, len=1),
 Token(form='9', tag='SN', start=1, len=1),
 Token(form='K', tag='SL', start=3, len=1),
 Token(form='55', tag='SN', start=4, len=2)]

**Comment by bab2min** [comment]
안녕하세요 @joinmateFirst 님, 오류 제보해주셔서 감사합니다.
#90에서도 비슷한 문제가 보고되어 다음 업데이트에서 수정하고자 작업중에 있습니다~

**Comment by bab2min** [comment]
@joinmateFirst 0.14.0버전에서 해당 버그는 수정되었습니다. 감사합니다~
