### ISSUE TITLE
문장 분리 문제

### ISSUE THREAD

**Issue by JeongChangsu** [bab2min/kiwipiepy#96]
~할까 걱정 => ~할까 / 걱정
~할까 봐요 => ~할까 / 봐요
~지 싶다 => ~지 / 싶다
~할까 싶다 => ~할까 / 싶다

하나의 문장으로 인식하지 못하고 분리되는 문제가 있네요.

키위 패키지 너무 잘 사용하고 있습니다. 연구 개발 정말 감사드립니다~ :)

**Comment by bab2min** [comment]
@JeongChangsu 
오류 제보에 감사드립니다~
모델이 위와 같은 문맥에서 `-ㄹ까`, `-지` 등의 형태소를 종결 어미(`EF`)로 분석하는 문제가 있나보네요.
다음 업데이트에서 개선해보도록 하겠습니다.
