### ISSUE TITLE
`Kiwi(typos="basic")`에서 에러가 발생하는 문제가 있습니다.

### ISSUE THREAD

**Issue by jongbeom-kim64** [bab2min/kiwipiepy#97]
"Segmentation fault: 11"라는 에러가 발생하는데, 모든 텍스트에 대해서 발생하지는 않습니다.

또한 라이브러리의 버전에 따라서 발생하기도, 발생하지 않기도 하는 것으로 보입니다.

반면 `typos=None`로 작성할 때는 에러가 발생하지 않습니다.

**Comment by KimRass** [comment]
저도 에러가 발생할 때의 정확한 버전은 모르겠네요...

지금 0.13.1에서는 정상적으로 실행됩니다.

**Comment by KimRass** [comment]
재설치 후 0.14.0 버전에서도 정상적으로 실행됨을 확인했습니다. 감사합니다.
