### ISSUE TITLE
ray 사용시 Kiwi 적용 불가 문제

### ISSUE THREAD

**Issue by smbslt3** [bab2min/kiwipiepy#99]
안녕하세요

대규모 텍스트 데이터를 kiwi 토크나이저를 사용해 토크나이징 하는데
속도를 높이기 위해 pandas의 apply 대신 modin을 사용해 멀티프로세싱으로 처리를 하려고 합니다.
modin의 backend로 ray를 사용한 경우, 아래와 같은 에러가 발생합니다

```python
df['tokens'] = df['text'].apply(tokenizer)
>>> TypeError: cannot pickle 'Kiwi' object
```

동일 코드를 사용해 modin이 아니라 pandas로 작업시 오래걸리지만 문제 없이 작업이 완료되는 것으로 보아
kiwi tokenizer가 ray와 혼용할 수 없는 것으로 보입니다

제가 개발자가 아니라서 이 이상은 자세히 말씀드리기가 어렵네요
한국어 토크나이저 중에 kiwi를 제일 잘 쓰고 있는데, 해결될 수 있는 문제였으면 합니다

**Comment by bab2min** [comment]
안녕하세요 @smbslt3 님, 좋은 의견 감사합니다.

해당 문제는 Python에서 multiprocessing 시 프로세스 간에 object를 공유하기 위해서 pickle을 사용하는데요,
Kiwi는 pickle로 주고받을수 없는 객체라서 발생하는 문제입니다.

일단 Kiwi의 경우 자체적으로 멀티스레딩을 지원합니다. (파이썬의 multiprocessing과는 다르게 프로세스 하나가 스레드풀을 공유하는 방식이므로 훨씬 효율적입니다.) 굳이 modin을 사용하시지 않더라도 다음과 같은 방법으로 멀티스레드를 이용해 pandas 내의 텍스트를 형태소분석할 수 있습니다.
```python
kiwi = Kiwi(num_workers=0) # 0으로 지정시 사용가능한 모든 코어 수에 맞춰 스레드를 생성. 
# 혹은 4, 8 등으로 명시적으로 지정하는 것도 가능함.

df['tokens'] = list(kiwi.tokenize(df['text']))
# kiwi.tokenize에 iterable한 객체를 입력할 경우 자동으로 멀티스레드로 분산하여 처리됨
# 처리 결과는 map 형태로 반환되므로 list로 변환하여야 df에 다시 입력 가능함.
```

modin에서도 작동가능하도록 pickling 및 unpickling을 구현하는 것도 방법이겠지만, Kiwi에서 자체적으로 지원하는 병렬처리에 비해 비효율적이고, 또 c++로 구현된 객체의 pickling의 경우 여러가지 복잡한 문제들이 있어 쉽지 않아보입니다. 그래서 당분간은 위의 방법으로 병렬처리를 하시는 걸 권장드립니다.

**Comment by smbslt3** [comment]
안내 감사합니다. 멀티 프로세싱을 하는건 알고 있었는데, 이런 방식으로도 작동하는 줄은 몰랐네요.
하나의 함수에서 토크나이징 후 후처리를 한 번에 하고 있었는데, 
알려주신 방법으로 토크나이징을 먼저 하고 후처리를 따로 했더니 토크나이징 시간이 35분에서 7분으로 줄었습니다.

한국어 자연어 처리에 큰 기여를 해주셔서 늘 감사합니다.
